{
 "title": "Component and File-level Metrics",
 "description": "This dashboard shows the metrics  collected by gitextractor plugin",
 "tags": [ "Engineering Leads Dashboard" ],
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repo_id",
    "label": "Repo",
    "query": "select concat(name, '--', id) as text from repos"
   },
   { "name": "selected_path", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Author dimension",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "commits distribution by author",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT author_name,\n        count(distinct commit_sha) AS commit_nums\nFROM commits\nJOIN repo_commits\nWHERE commits.sha =repo_commits.commit_sha\n        AND repo_commits.repo_id IN (${repo_id})\n        AND $__timeFilter(commits.authored_date)\nGROUP BY  author_name,author_id\nORDER BY  commit_nums desc\nLIMIT 10; "
    }
   ]
  },
  {
   "title": "lines of code distribution by author",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT author_name,\n         sum(additions-deletions) AS cnt\nFROM commits\nJOIN repo_commits\nWHERE commits.sha =repo_commits.commit_sha\n        AND repo_commits.repo_id IN (${repo_id})\n        AND $__timeFilter(commits.authored_date)\nGROUP BY  author_name,author_id\nORDER BY  cnt DESC \nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Time dimension",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "commits distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE cast(dayofweek(authored_date) AS char) \n    WHEN '2' THEN '1.Monday'\n    WHEN '3' THEN '2.Tuesday'\n    WHEN '4' THEN '3.Wednesday'\n    WHEN '5' THEN '4.Thursday'\n    WHEN '6' THEN '5.Friday'\n    WHEN '7' THEN '6.Saturday'\n    WHEN '1' THEN '7.Sunday'\n    END AS weekday , count(distinct commit_sha) AS commit_nums\nFROM commits\nJOIN repo_commits\nWHERE $__timeFilter(commits.authored_date)\n        AND commits.sha =repo_commits.commit_sha\n        AND repo_commits.repo_id IN (${repo_id})\nGROUP BY  weekday\n"
    }
   ]
  },
  {
   "title": "lines of code distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE cast(dayofweek(authored_date) AS char)\n    WHEN '2' THEN '1.Monday'\n    WHEN '3' THEN '2.Tuesday'\n    WHEN '4' THEN '3.Wednesday'\n    WHEN '5' THEN '4.Thursday'\n    WHEN '6' THEN '5.Friday'\n    WHEN '7' THEN '6.Saturday'\n    WHEN '1' THEN '7.Sunday'\n    END AS weekday , sum(additions-deletions) AS changed_nums, sum(additions) AS total_additions, sum(deletions) AS total_deletions\nFROM commits\nJOIN repo_commits\nWHERE commits.sha =repo_commits.commit_sha\n        AND repo_commits.repo_id IN (${repo_id})\n        AND $__timeFilter(commits.authored_date)\nGROUP BY  weekday\nORDER BY  weekday"
    }
   ]
  },
  {
   "title": "File dimension",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Files with maximum number of authors",
   "type": "barchart",
   "description": "Please disable the SkipCommitFiles in the .env setting to view this metric. However, this will significantly increase the time to collect data.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT \n    file_path,\n    count(distinct c.author_name) AS cnt\nFROM commits c\n    JOIN commit_files cf on cf.commit_sha = c.sha\n    JOIN repo_commits rc ON cf.commit_sha = rc.commit_sha\nWHERE \n    repo_id IN (${repo_id})\n    AND $__timeFilter(c.authored_date)\n    AND CONVERT(file_path USING utf8mb4) REGEXP '${selected_path:raw}'\nGROUP BY file_path\nORDER BY cnt DESC \nlimit 10;"
    }
   ]
  },
  {
   "title": "[Selected Files] Largest files with lowest number of authors",
   "type": "table",
   "description": "Please disable the SkipCommitFiles in the .env setting to view this metric. However, this will significantly increase the time to collect data.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT file_path,\n       COUNT(DISTINCT author_name) AS author_count,\n       MAX(rst) AS lines_of_code,\n       MAX(rst) / COUNT(DISTINCT author_name) AS rate\nFROM commits\nJOIN (\n  SELECT file_path,\n         commit_files.commit_sha,\n         SUM(additions - deletions) AS rst\n  FROM commit_files\n  JOIN repo_commits rc ON commit_files.commit_sha = rc.commit_sha\n  WHERE \n    repo_id IN (${repo_id})\n    AND CONVERT(file_path USING utf8mb4) REGEXP '${selected_path:raw}'\n  GROUP BY file_path, commit_files.commit_sha\n) a ON a.commit_sha = commits.sha\nGROUP BY file_path\nHAVING author_count > 0\nORDER BY rate DESC\n"
    }
   ]
  },
  {
   "title": "Files with most modifications",
   "type": "barchart",
   "description": "Please disable the SkipCommitFiles in the .env setting to view this metric. However, this will significantly increase the time to collect data.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT \n    file_path,\n    count(distinct sha) AS modified_num\nFROM commits c\n    JOIN commit_files cf on cf.commit_sha = c.sha\n    JOIN repo_commits rc ON cf.commit_sha = rc.commit_sha\nWHERE \n    repo_id IN (${repo_id})\n    AND $__timeFilter(c.authored_date)\n    AND CONVERT(file_path USING utf8mb4) REGEXP '${selected_path:raw}'\nGROUP BY file_path\nORDER BY modified_num desc\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "[All Files] Files with most modifications",
   "type": "barchart",
   "description": "Please disable the SkipCommitFiles in the .env setting to view this metric. However, this will significantly increase the time to collect data.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT \n    file_path,\n    count(distinct sha) AS cnt\nFROM commits c \n    JOIN commit_files cf on cf.commit_sha = c.sha \n    JOIN repo_commits rc ON cf.commit_sha = rc.commit_sha\nWHERE \n    repo_id IN (${repo_id}) \n    AND $__timeFilter(c.authored_date)\nGROUP BY file_path\nORDER BY cnt desc\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Lineage dimension",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "In which day the code has highest chance to stay in repository.",
   "type": "barchart",
   "description": "Please disable the SkipCommitFiles in the .env setting to view this metric. However, this will significantly increase the time to collect data.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT    \n    CASE cast(dayofweek(commits.committed_date) AS char)\n        WHEN '2' THEN '1.Monday'\n        WHEN '3' THEN '2.Tuesday'\n        WHEN '4' THEN '3.Wednesday'\n        WHEN '5' THEN '4.Thursday'\n        WHEN '6' THEN '5.Friday'\n        WHEN '7' THEN '6.Saturday'\n        WHEN '1' THEN '7.Sunday'\n        END AS wd,\n    count(*) as lived_lines\nFROM repo_snapshot\n    JOIN commits\n    ON commits.sha=repo_snapshot.commit_sha\nWHERE \n    repo_snapshot.repo_id IN (${repo_id})\n    AND $__timeFilter(commits.committed_date)\nGROUP BY  wd\nORDER BY  wd ;"
    }
   ]
  },
  {
   "title": "Which file has the longest average line age?",
   "type": "table",
   "description": "Please disable the SkipCommitFiles in the .env setting to view this metric. However, this will significantly increase the time to collect data.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT file_path,\n        avg(timestampdiff(day,\n        commits.committed_date,\n        now())) AS line_age\nFROM repo_snapshot\nJOIN commits\n    ON repo_snapshot.commit_sha = commits.sha\nWHERE repo_snapshot.repo_id IN (${repo_id})\n    AND $__timeFilter(commits.committed_date)\nGROUP BY  file_path\nORDER BY  line_age desc \nLIMIT 20;"
    }
   ]
  }
 ]
}