{
 "title": "DORA",
 "tags": [
  "Engineering Leads Dashboard",
  "Highlights",
  "DORA"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "select distinct name from projects"
   },
   {
    "name": "dora_report",
    "label": "DORA Report",
    "query": "select dora_report from dora_benchmarks"
   },
   {
    "name": "title_value",
    "label": "TitleValue",
    "query": "SELECT \n  CASE \n    WHEN dora_report = '2023' THEN \"Failed Deployment Recovery Time\"\n    WHEN dora_report = '2021' THEN \"Median Time to Restore Service\"\n    ELSE NULL \n  END AS title_value\nFROM dora_benchmarks\nWHERE dora_report = '${dora_report:raw}'"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- See [how to config](https://devlake.apache.org/docs/DORA) this dashboard\n- Data Sources Required: \n  - `Deployments` from Jenkins, GitLab CI, GitHub Action, webhook, etc. \n  - `Pull Requests` from GitHub PRs, GitLab MRs, BitBucket PRs, Azure DevOps PRs, etc.\n  - `Incidents` from Jira issues, GitHub issues, TAPD issues, PagerDuty Incidents, etc. \n- Transformation Required: Define `deployments` and `incidents` in [data transformations](https://devlake.apache.org/docs/Configuration/Tutorial#step-3---add-transformations-optional) while configuring the blueprint of a project.\n- You can validate/debug this dashboard with the [DORA validation dashboard](/grafana/d/KGkUnV-Vz/dora-dashboard-validation)\n- DORA benchmarks vary in different years. You can switch the benchmarks to change them.\n- In DORA's official report in 2023, metric 'failed deployment recovery time' has replaced 'MTTR'."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overall DORA Metrics",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "-- Metric 1: Deployment Frequency\nwith last_few_calendar_months as(\n  -- construct the last few calendar months within the selected time period in the top-right corner\n  SELECT\n    CAST(($__timeTo() - INTERVAL (H + T + U) DAY) AS date) day\n  FROM\n    (\n      SELECT\n        0 H\n      UNION\n      ALL\n      SELECT\n        100\n      UNION\n      ALL\n      SELECT\n        200\n      UNION\n      ALL\n      SELECT\n        300\n    ) H\n    CROSS JOIN (\n      SELECT\n        0 T\n      UNION\n      ALL\n      SELECT\n        10\n      UNION\n      ALL\n      SELECT\n        20\n      UNION\n      ALL\n      SELECT\n        30\n      UNION\n      ALL\n      SELECT\n        40\n      UNION\n      ALL\n      SELECT\n        50\n      UNION\n      ALL\n      SELECT\n        60\n      UNION\n      ALL\n      SELECT\n        70\n      UNION\n      ALL\n      SELECT\n        80\n      UNION\n      ALL\n      SELECT\n        90\n    ) T\n    CROSS JOIN (\n      SELECT\n        0 U\n      UNION\n      ALL\n      SELECT\n        1\n      UNION\n      ALL\n      SELECT\n        2\n      UNION\n      ALL\n      SELECT\n        3\n      UNION\n      ALL\n      SELECT\n        4\n      UNION\n      ALL\n      SELECT\n        5\n      UNION\n      ALL\n      SELECT\n        6\n      UNION\n      ALL\n      SELECT\n        7\n      UNION\n      ALL\n      SELECT\n        8\n      UNION\n      ALL\n      SELECT\n        9\n    ) U\n  WHERE\n    ($__timeTo() - INTERVAL (H + T + U) DAY) > $__timeFrom()\n),\n_production_deployment_days as(\n  -- When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date.\n  SELECT\n    cdc.cicd_deployment_id as deployment_id,\n    max(DATE(cdc.finished_date)) as day\n  FROM\n    cicd_deployment_commits cdc\n    JOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id\n    and pm.`table` = 'cicd_scopes'\n  WHERE\n    pm.project_name in (${project})\n    and cdc.result = 'SUCCESS'\n    and cdc.environment = 'PRODUCTION'\n  GROUP BY\n    1\n),\n_days_weekly_deploy as(\n  -- calculate the number of deployment days every week\n  SELECT\n    date(\n      DATE_ADD(\n        last_few_calendar_months.day,\n        INTERVAL - WEEKDAY(last_few_calendar_months.day) DAY\n      )\n    ) as week,\n    MAX(\n      if(\n        _production_deployment_days.day is not null,\n        1,\n        0\n      )\n    ) as weeks_deployed,\n    COUNT(distinct _production_deployment_days.day) as days_deployed\n  FROM\n    last_few_calendar_months\n    LEFT JOIN _production_deployment_days ON _production_deployment_days.day = last_few_calendar_months.day\n  GROUP BY\n    week\n),\n_days_monthly_deploy as(\n  -- calculate the number of deployment days every month\n  SELECT\n    date(\n      DATE_ADD(\n        last_few_calendar_months.day,\n        INTERVAL - DAY(last_few_calendar_months.day) + 1 DAY\n      )\n    ) as month,\n    MAX(\n      if(\n        _production_deployment_days.day is not null,\n        1,\n        null\n      )\n    ) as months_deployed,\n    COUNT(distinct _production_deployment_days.day) as days_deployed\n  FROM\n    last_few_calendar_months\n    LEFT JOIN _production_deployment_days ON _production_deployment_days.day = last_few_calendar_months.day\n  GROUP BY\n    month\n),\n_days_six_months_deploy AS (\n  SELECT\n    month,\n    SUM(days_deployed) OVER (\n      ORDER BY\n        month ROWS BETWEEN 5 PRECEDING\n        AND CURRENT ROW\n    ) AS days_deployed_per_six_months,\n    COUNT(months_deployed) OVER (\n      ORDER BY\n        month ROWS BETWEEN 5 PRECEDING\n        AND CURRENT ROW\n    ) AS months_deployed_count,\n    ROW_NUMBER() OVER (\n      PARTITION BY DATE_FORMAT(month, '%Y-%m') DIV 6\n      ORDER BY\n        month DESC\n    ) AS rn\n  FROM\n    _days_monthly_deploy\n),\n_median_number_of_deployment_days_per_week_ranks as(\n  SELECT\n    *,\n    percent_rank() over(\n      order by\n        days_deployed\n    ) as ranks\n  FROM\n    _days_weekly_deploy\n),\n_median_number_of_deployment_days_per_week as(\n  SELECT\n    max(days_deployed) as median_number_of_deployment_days_per_week\n  FROM\n    _median_number_of_deployment_days_per_week_ranks\n  WHERE\n    ranks <= 0.5\n),\n_median_number_of_deployment_days_per_month_ranks as(\n  SELECT\n    *,\n    percent_rank() over(\n      order by\n        days_deployed\n    ) as ranks\n  FROM\n    _days_monthly_deploy\n),\n_median_number_of_deployment_days_per_month as(\n  SELECT\n    max(days_deployed) as median_number_of_deployment_days_per_month\n  FROM\n    _median_number_of_deployment_days_per_month_ranks\n  WHERE\n    ranks <= 0.5\n),\n_days_per_six_months_deploy_by_filter AS (\n  SELECT\n    month,\n    days_deployed_per_six_months,\n    months_deployed_count\n  FROM\n    _days_six_months_deploy\n  WHERE\n    rn % 6 = 1\n),\n_median_number_of_deployment_days_per_six_months_ranks as(\n  SELECT\n    *,\n    percent_rank() over(\n      order by\n        days_deployed_per_six_months\n    ) as ranks\n  FROM\n    _days_per_six_months_deploy_by_filter\n),\n_median_number_of_deployment_days_per_six_months as(\n  SELECT\n    min(days_deployed_per_six_months) as median_number_of_deployment_days_per_six_months,\n    min(months_deployed_count) as is_collected\n  FROM\n    _median_number_of_deployment_days_per_six_months_ranks\n  WHERE\n    ranks >= 0.5\n),\n_metric_deployment_frequency as (\n  SELECT\n    'Deployment frequency' as metric,\n    CASE\n      WHEN ('$dora_report') = '2023' THEN CASE\n        WHEN median_number_of_deployment_days_per_week >= 5 THEN 'On-demand(elite)'\n        WHEN median_number_of_deployment_days_per_week >= 1 THEN 'Between once per day and once per week(high)'\n        WHEN median_number_of_deployment_days_per_month >= 1 THEN 'Between once per week and once per month(medium)'\n        WHEN median_number_of_deployment_days_per_month < 1\n        and is_collected is not null THEN 'Fewer than once per month(low)'\n        ELSE \"N/A. Please check if you have collected deployments.\"\n      END\n      WHEN ('$dora_report') = '2021' THEN CASE\n        WHEN median_number_of_deployment_days_per_week >= 5 THEN 'On-demand(elite)'\n        WHEN median_number_of_deployment_days_per_month >= 1 THEN 'Between once per day and once per month(high)'\n        WHEN median_number_of_deployment_days_per_six_months >= 1 THEN 'Between once per month and once every 6 months(medium)'\n        WHEN median_number_of_deployment_days_per_six_months < 1\n        and is_collected is not null THEN 'Fewer than once per six months(low)'\n        ELSE \"N/A. Please check if you have collected deployments.\"\n      END\n      ELSE 'Invalid dora report'\n    END AS value\n  FROM\n    _median_number_of_deployment_days_per_week,\n    _median_number_of_deployment_days_per_month,\n    _median_number_of_deployment_days_per_six_months\n),\n-- Metric 2: median lead time for changes\n_pr_stats as (\n  -- get the cycle time of PRs deployed by the deployments finished in the selected period\n  SELECT\n    distinct pr.id,\n    ppm.pr_cycle_time\n  FROM\n    pull_requests pr\n    join project_pr_metrics ppm on ppm.id = pr.id\n    join project_mapping pm on pr.base_repo_id = pm.row_id\n    and pm.`table` = 'repos'\n    join cicd_deployment_commits cdc on ppm.deployment_commit_id = cdc.id\n  WHERE\n    pm.project_name in (${project})\n    and pr.merged_date is not null\n    and ppm.pr_cycle_time is not null\n    and $__timeFilter(cdc.finished_date)\n),\n_median_change_lead_time_ranks as(\n  SELECT\n    *,\n    percent_rank() over(\n      order by\n        pr_cycle_time\n    ) as ranks\n  FROM\n    _pr_stats\n),\n_median_change_lead_time as(\n  -- use median PR cycle time as the median change lead time\n  SELECT\n    max(pr_cycle_time) as median_change_lead_time\n  FROM\n    _median_change_lead_time_ranks\n  WHERE\n    ranks <= 0.5\n),\n_metric_change_lead_time as (\n  SELECT\n    'Lead time for changes' as metric,\n    CASE\n      WHEN ('$dora_report') = '2023' THEN CASE\n        WHEN median_change_lead_time < 24 * 60 THEN \"Less than one day(elite)\"\n        WHEN median_change_lead_time < 7 * 24 * 60 THEN \"Between one day and one week(high)\"\n        WHEN median_change_lead_time < 30 * 24 * 60 THEN \"Between one week and one month(medium)\"\n        WHEN median_change_lead_time >= 30 * 24 * 60 THEN \"More than one month(low)\"\n        ELSE \"N/A. Please check if you have collected deployments/pull_requests.\"\n      END\n      WHEN ('$dora_report') = '2021' THEN CASE\n        WHEN median_change_lead_time < 60 THEN \"Less than one hour(elite)\"\n        WHEN median_change_lead_time < 7 * 24 * 60 THEN \"Less than one week(high)\"\n        WHEN median_change_lead_time < 180 * 24 * 60 THEN \"Between one week and six months(medium)\"\n        WHEN median_change_lead_time >= 180 * 24 * 60 THEN \"More than six months(low)\"\n        ELSE \"N/A. Please check if you have collected deployments/pull_requests.\"\n      END\n      ELSE 'Invalid dora report'\n    END AS value\n  FROM\n    _median_change_lead_time\n),\n-- Metric 3: change failure rate\n_deployments as (\n  -- When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date.\n  SELECT\n    cdc.cicd_deployment_id as deployment_id,\n    max(cdc.finished_date) as deployment_finished_date\n  FROM\n    cicd_deployment_commits cdc\n    JOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id\n    and pm.`table` = 'cicd_scopes'\n  WHERE\n    pm.project_name in (${project})\n    and cdc.result = 'SUCCESS'\n    and cdc.environment = 'PRODUCTION'\n  GROUP BY\n    1\n  HAVING\n    $__timeFilter(max(cdc.finished_date))\n),\n_failure_caused_by_deployments as (\n  -- calculate the number of incidents caused by each deployment\n  SELECT\n    d.deployment_id,\n    d.deployment_finished_date,\n    count(\n      distinct case\n        when i.id is not null then d.deployment_id\n        else null\n      end\n    ) as has_incident\n  FROM\n    _deployments d\n    left join project_incident_deployment_relationships pim on d.deployment_id = pim.deployment_id\n    left join incidents i on pim.id = i.id\n  GROUP BY\n    1,\n    2\n),\n_change_failure_rate as (\n  SELECT\n    case\n      when count(deployment_id) is null then null\n      else sum(has_incident) / count(deployment_id)\n    end as change_failure_rate\n  FROM\n    _failure_caused_by_deployments\n),\n_is_collected_data as(\n  SELECT\n    CASE\n      WHEN COUNT(i.id) = 0\n      AND COUNT(cdc.id) = 0 THEN 'No All'\n      WHEN COUNT(i.id) = 0 THEN 'No Incidents'\n      WHEN COUNT(cdc.id) = 0 THEN 'No Deployments'\n    END AS is_collected\n  FROM\n    (\n      SELECT\n        1\n    ) AS dummy\n    LEFT JOIN incidents i ON 1 = 1\n    LEFT JOIN cicd_deployment_commits cdc ON 1 = 1\n),\n_metric_cfr as (\n  SELECT\n    'Change failure rate' as metric,\n    CASE\n      WHEN ('$dora_report') = '2023' THEN CASE\n        WHEN is_collected = \"No All\" THEN \"N/A. Please check if you have collected deployments/incidents.\"\n        WHEN is_collected = \"No Incidents\" THEN \"N/A. Please check if you have collected incidents.\"\n        WHEN is_collected = \"No Deployments\" THEN \"N/A. Please check if you have collected deployments.\"\n        WHEN change_failure_rate <=.05 THEN \"0-5%(elite)\"\n        WHEN change_failure_rate <=.10 THEN \"5%-10%(high)\"\n        WHEN change_failure_rate <=.15 THEN \"10%-15%(medium)\"\n        WHEN change_failure_rate >.15 THEN \"> 15%(low)\"\n        ELSE \"N/A. Please check if you have collected deployments/incidents.\"\n      END\n      WHEN ('$dora_report') = '2021' THEN CASE\n        WHEN is_collected = \"No All\" THEN \"N/A. Please check if you have collected deployments/incidents.\"\n        WHEN is_collected = \"No Incidents\" THEN \"N/A. Please check if you have collected incidents.\"\n        WHEN is_collected = \"No Deployments\" THEN \"N/A. Please check if you have collected deployments.\"\n        WHEN change_failure_rate <=.15 THEN \"0-15%(elite)\"\n        WHEN change_failure_rate <=.20 THEN \"16%-20%(high)\"\n        WHEN change_failure_rate <=.30 THEN \"21%-30%(medium)\"\n        WHEN change_failure_rate >.30 THEN \"> 30%(low)\"\n        ELSE \"N/A. Please check if you have collected deployments/incidents.\"\n      END\n      ELSE 'Invalid dora report'\n    END AS value\n  FROM\n    _change_failure_rate,\n    _is_collected_data\n),\n--  ***** 2023 report ***** --\n--  Metric 4: Failed deployment recovery time\n_incidents_for_deployments as (\n  SELECT\n    i.id as incident_id,\n    i.created_date as incident_create_date,\n    i.resolution_date as incident_resolution_date,\n    fd.deployment_id as caused_by_deployment,\n    fd.deployment_finished_date,\n    date_format(fd.deployment_finished_date, '%y/%m') as deployment_finished_month\n  FROM\n    incidents i\n    left join project_incident_deployment_relationships pim on i.id = pim.id\n    join _deployments fd on pim.deployment_id = fd.deployment_id\n  WHERE\n    $__timeFilter(i.resolution_date)\n),\n_recovery_time_ranks as (\n  SELECT\n    *,\n    percent_rank() over(\n      order by\n        TIMESTAMPDIFF(\n          MINUTE,\n          deployment_finished_date,\n          incident_resolution_date\n        )\n    ) as ranks\n  FROM\n    _incidents_for_deployments\n),\n_median_recovery_time as (\n  SELECT\n    max(\n      TIMESTAMPDIFF(\n        MINUTE,\n        deployment_finished_date,\n        incident_resolution_date\n      )\n    ) as median_recovery_time\n  FROM\n    _recovery_time_ranks\n  WHERE\n    ranks <= 0.5\n),\n_metric_recovery_time_2023_report as(\n  SELECT\n    \"Failed deployment recovery time\" as metric,\n    CASE\n      WHEN ('$dora_report') = '2023' THEN CASE\n        WHEN median_recovery_time < 60 THEN \"Less than one hour(elite)\"\n        WHEN median_recovery_time < 24 * 60 THEN \"Less than one day(high)\"\n        WHEN median_recovery_time < 7 * 24 * 60 THEN \"Between one day and one week(medium)\"\n        WHEN median_recovery_time >= 7 * 24 * 60 THEN \"More than one week(low)\"\n        ELSE \"N/A. Please check if you have collected deployments or incidents.\"\n      END\n    END AS median_recovery_time\n  FROM\n    _median_recovery_time\n),\n--  ***** 2021 report ***** --\n-- Metric 4: Median time to restore service \n_incidents as (\n  -- get the incidents created within the selected time period in the top-right corner\n  SELECT\n    distinct i.id,\n    cast(lead_time_minutes as signed) as lead_time_minutes\n  FROM\n    incidents i\n    join project_mapping pm on i.scope_id = pm.row_id\n    and pm.`table` = i.`table`\n  WHERE\n    pm.project_name in (${project})\n    and $__timeFilter(i.resolution_date)\n),\n_median_mttr_ranks as(\n  SELECT\n    *,\n    percent_rank() over(\n      order by\n        lead_time_minutes\n    ) as ranks\n  FROM\n    _incidents\n),\n_median_mttr as(\n  SELECT\n    max(lead_time_minutes) as median_time_to_resolve\n  FROM\n    _median_mttr_ranks\n  WHERE\n    ranks <= 0.5\n),\n_metric_mttr_2021_report as(\n  SELECT\n    \"Time to restore service\" as metric,\n    CASE\n      WHEN ('$dora_report') = '2021' THEN CASE\n        WHEN median_time_to_resolve < 60 THEN \"Less than one hour(elite)\"\n        WHEN median_time_to_resolve < 24 * 60 THEN \"Less than one day(high)\"\n        WHEN median_time_to_resolve < 7 * 24 * 60 THEN \"Between one day and one week(medium)\"\n        WHEN median_time_to_resolve >= 7 * 24 * 60 THEN \"More than one week(low)\"\n        ELSE \"N/A. Please check if you have collected incidents.\"\n      END\n    END AS median_time_to_resolve\n  FROM\n    _median_mttr\n),\n_metric_mrt_or_mm as(\n  SELECT\n    metric,\n    median_recovery_time AS value\n  FROM\n    _metric_recovery_time_2023_report\n  WHERE\n    ('$dora_report') = '2023'\n  UNION\n  SELECT\n    metric,\n    median_time_to_resolve AS value\n  FROM\n    _metric_mttr_2021_report\n  WHERE\n    ('$dora_report') = '2021'\n),\n_final_results as (\n  SELECT\n    distinct db.id,\n    db.metric,\n    db.low,\n    db.medium,\n    db.high,\n    db.elite,\n    m1.metric as _metric,\n    m1.value\n  FROM\n    dora_benchmarks db\n    left join _metric_deployment_frequency m1 on db.metric = m1.metric\n  WHERE\n    m1.metric is not null\n    and db.dora_report = ('$dora_report')\n  union\n  SELECT\n    distinct db.id,\n    db.metric,\n    db.low,\n    db.medium,\n    db.high,\n    db.elite,\n    m2.metric as _metric,\n    m2.value\n  FROM\n    dora_benchmarks db\n    left join _metric_change_lead_time m2 on db.metric = m2.metric\n  WHERE\n    m2.metric is not null\n    and db.dora_report = ('$dora_report')\n  union\n  SELECT\n    distinct db.id,\n    db.metric,\n    db.low,\n    db.medium,\n    db.high,\n    db.elite,\n    m3.metric as _metric,\n    m3.value\n  FROM\n    dora_benchmarks db\n    left join _metric_cfr m3 on db.metric = m3.metric\n  WHERE\n    m3.metric is not null\n    and db.dora_report = ('$dora_report')\n  union\n  SELECT\n    distinct db.id,\n    db.metric,\n    db.low,\n    db.medium,\n    db.high,\n    db.elite,\n    m4.metric as _metric,\n    m4.value\n  FROM\n    dora_benchmarks db\n    left join _metric_mrt_or_mm m4 on db.metric = m4.metric\n  WHERE\n    m4.metric is not null\n    and db.dora_report = ('$dora_report')\n)\nSELECT\n  metric,\n  replace(metric, ' ', '-') as metric_hidden,\n  case\n    when low = value then low\n    else null\n  end as low,\n  case\n    when medium = value then medium\n    else null\n  end as medium,\n  case\n    when high = value then high\n    else null\n  end as high,\n  case\n    when elite = value then elite\n    else null\n  end as elite\nFROM\n  _final_results\nORDER BY\n  id"
    }
   ]
  },
  {
   "title": "Deployment Frequency",
   "type": "stat",
   "description": "How often an organization deploys code to production or release it to end users\n\n# 2023 Benchmarks\n- **Elite**: >= 7 deployment days per week\n- **High**: >= 1 deployment day per week\n- **Medium**: >= 1 deployment day per month\n- **Low**: < 1 deployment day per month\n# 2021 Benchmarks\n- **Elite**: >= 7 deployment days per week\n- **High**: >= 1 deployment day per month\n- **Medium**: >= 1  deployment day per six months\n- **Low**: < 1 deployment day per six months",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Metric 1: Deployment Frequency\nwith last_few_calendar_months as(\n-- construct the last few calendar months within the selected time period in the top-right corner\n\tSELECT CAST(($__timeTo()-INTERVAL (H+T+U) DAY) AS date) day\n\tFROM ( SELECT 0 H\n\t\t\tUNION ALL SELECT 100 UNION ALL SELECT 200 UNION ALL SELECT 300\n\t\t) H CROSS JOIN ( SELECT 0 T\n\t\t\tUNION ALL SELECT  10 UNION ALL SELECT  20 UNION ALL SELECT  30\n\t\t\tUNION ALL SELECT  40 UNION ALL SELECT  50 UNION ALL SELECT  60\n\t\t\tUNION ALL SELECT  70 UNION ALL SELECT  80 UNION ALL SELECT  90\n\t\t) T CROSS JOIN ( SELECT 0 U\n\t\t\tUNION ALL SELECT   1 UNION ALL SELECT   2 UNION ALL SELECT   3\n\t\t\tUNION ALL SELECT   4 UNION ALL SELECT   5 UNION ALL SELECT   6\n\t\t\tUNION ALL SELECT   7 UNION ALL SELECT   8 UNION ALL SELECT   9\n\t\t) U\n\tWHERE\n\t\t($__timeTo()-INTERVAL (H+T+U) DAY) > $__timeFrom()\n),\n\n_production_deployment_days as(\n-- When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date.\n\tSELECT\n\t\tcdc.cicd_deployment_id as deployment_id,\n\t\tmax(DATE(cdc.finished_date)) as day\n\tFROM cicd_deployment_commits cdc\n\tJOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id and pm.`table` = 'cicd_scopes'\n\tWHERE\n\t\tpm.project_name in (${project})\n\t\tand cdc.result = 'SUCCESS'\n\t\tand cdc.environment = 'PRODUCTION'\n\tGROUP BY 1\n),\n\n_days_weekly_deploy as(\n-- calculate the number of deployment days every week\n\tSELECT\n\t\t\tdate(DATE_ADD(last_few_calendar_months.day, INTERVAL -WEEKDAY(last_few_calendar_months.day) DAY)) as week,\n\t\t\tMAX(if(_production_deployment_days.day is not null, 1, null)) as weeks_deployed,\n\t\t\tCOUNT(distinct _production_deployment_days.day) as days_deployed\n\tFROM \n\t\tlast_few_calendar_months\n\t\tLEFT JOIN _production_deployment_days ON _production_deployment_days.day = last_few_calendar_months.day\n\tGROUP BY week\n\t),\n\n_days_monthly_deploy as(\n-- calculate the number of deployment days every month\n\tSELECT\n\t\t\tdate(DATE_ADD(last_few_calendar_months.day, INTERVAL -DAY(last_few_calendar_months.day)+1 DAY)) as month,\n\t\t\tMAX(if(_production_deployment_days.day is not null, 1, null)) as months_deployed,\n\t\t  COUNT(distinct _production_deployment_days.day) as days_deployed\n\tFROM \n\t\tlast_few_calendar_months\n\t\tLEFT JOIN _production_deployment_days ON _production_deployment_days.day = last_few_calendar_months.day\n\tGROUP BY month\n\t),\n\n_days_six_months_deploy AS (\n  SELECT\n    month,\n    SUM(days_deployed) OVER (\n      ORDER BY month\n      ROWS BETWEEN 5 PRECEDING AND CURRENT ROW\n    ) AS days_deployed_per_six_months,\n    COUNT(months_deployed) OVER (\n      ORDER BY month\n      ROWS BETWEEN 5 PRECEDING AND CURRENT ROW\n    ) AS months_deployed_count,\n    ROW_NUMBER() OVER (\n      PARTITION BY DATE_FORMAT(month, '%Y-%m') DIV 6\n      ORDER BY month DESC\n    ) AS rn\n  FROM _days_monthly_deploy\n),\n\n_median_number_of_deployment_days_per_week_ranks as(\n\tSELECT *, percent_rank() over(order by days_deployed) as ranks\n\tFROM _days_weekly_deploy\n),\n\n_median_number_of_deployment_days_per_week as(\n\tSELECT max(days_deployed) as median_number_of_deployment_days_per_week\n\tFROM _median_number_of_deployment_days_per_week_ranks\n\tWHERE ranks <= 0.5\n),\n\n_median_number_of_deployment_days_per_month_ranks as(\n\tSELECT *, percent_rank() over(order by days_deployed) as ranks\n\tFROM _days_monthly_deploy\n),\n\n_median_number_of_deployment_days_per_month as(\n\tSELECT max(days_deployed) as median_number_of_deployment_days_per_month\n\tFROM _median_number_of_deployment_days_per_month_ranks\n\tWHERE ranks <= 0.5\n),\n\n_days_per_six_months_deploy_by_filter AS (\nSELECT\n  month,\n  days_deployed_per_six_months,\n  months_deployed_count\nFROM _days_six_months_deploy\nWHERE rn%6 = 1\n),\n\n\n_median_number_of_deployment_days_per_six_months_ranks as(\n\tSELECT *, percent_rank() over(order by days_deployed_per_six_months) as ranks\n\tFROM _days_per_six_months_deploy_by_filter\n),\n\n_median_number_of_deployment_days_per_six_months as(\n\tSELECT min(days_deployed_per_six_months) as median_number_of_deployment_days_per_six_months, min(months_deployed_count) as is_collected\n\tFROM _median_number_of_deployment_days_per_six_months_ranks\n\tWHERE ranks >= 0.5\n)\n\nSELECT \n  CASE\n    WHEN ('$dora_report') = '2023' THEN\n\t\t\tCASE  \n\t\t\t\tWHEN median_number_of_deployment_days_per_week >= 5 THEN CONCAT(median_number_of_deployment_days_per_week, ' deployment days per week(elite)')\n\t\t\t\tWHEN median_number_of_deployment_days_per_week >= 1 THEN CONCAT(median_number_of_deployment_days_per_week, ' deployment days per week(high)')\n\t\t\t\tWHEN median_number_of_deployment_days_per_month >= 1 THEN CONCAT(median_number_of_deployment_days_per_month, ' deployment days per month(medium)')\n\t\t\t\tWHEN median_number_of_deployment_days_per_month < 1 and is_collected is not null THEN CONCAT(median_number_of_deployment_days_per_month, ' deployment days per month(low)')\n\t\t\t\tELSE \"N/A. Please check if you have collected deployments.\" END\n\t \tWHEN ('$dora_report') = '2021' THEN\n\t\t\tCASE  \n\t\t\t\tWHEN median_number_of_deployment_days_per_week >= 5 THEN CONCAT(median_number_of_deployment_days_per_week, ' deployment days per week(elite)')\n\t\t\t\tWHEN median_number_of_deployment_days_per_month >= 1 THEN CONCAT(median_number_of_deployment_days_per_month, ' deployment days per month(high)')\n\t\t\t\tWHEN median_number_of_deployment_days_per_six_months >= 1 THEN CONCAT(median_number_of_deployment_days_per_six_months, ' deployment days per six months(medium)')\n\t\t\t\tWHEN median_number_of_deployment_days_per_six_months < 1 and is_collected is not null THEN CONCAT(median_number_of_deployment_days_per_six_months, ' deployment days per six months(low)')\n\t\t\t\tELSE \"N/A. Please check if you have collected deployments.\" END\n\t\tELSE 'Invalid dora report'\n\tEND AS 'Deployment Frequency'\nFROM _median_number_of_deployment_days_per_week, _median_number_of_deployment_days_per_month, _median_number_of_deployment_days_per_six_months\n"
    }
   ]
  },
  {
   "title": "Median Lead Time for Changes In Hours",
   "type": "stat",
   "description": "The median amount of time for a code change to be deployed into production.\n\n\n# 2023 Benchmarks\n- **Elite**: Less than one day\n- **High**: Between one day and one week\n- **Medium**: Between one week and one month\n- **Low**: More than one month\n# 2021 Benchmarks\n- **Elite**: Less than one hour\n- **High**: Less than one week\n- **Medium**: Between one week and six months\n- **Low**: More than six months\n",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Metric 2: median lead time for changes\nwith _pr_stats as (\n-- get the cycle time of PRs deployed by the deployments finished in the selected period\n\tSELECT\n\t\tdistinct pr.id,\n\t\tppm.pr_cycle_time\n\tFROM\n\t\tpull_requests pr \n\t\tjoin project_pr_metrics ppm on ppm.id = pr.id\n\t\tjoin project_mapping pm on pr.base_repo_id = pm.row_id and pm.`table` = 'repos'\n\t\tjoin cicd_deployment_commits cdc on ppm.deployment_commit_id = cdc.id\n\tWHERE\n\t  pm.project_name in (${project}) \n\t\tand pr.merged_date is not null\n\t\tand ppm.pr_cycle_time is not null\n\t\tand $__timeFilter(cdc.finished_date)\n),\n\n_median_change_lead_time_ranks as(\n\tSELECT *, percent_rank() over(order by pr_cycle_time) as ranks\n\tFROM _pr_stats\n),\n\n_median_change_lead_time as(\n-- use median PR cycle time as the median change lead time\n\tSELECT max(pr_cycle_time) as median_change_lead_time\n\tFROM _median_change_lead_time_ranks\n\tWHERE ranks <= 0.5\n)\n\nSELECT \n  CASE\n    WHEN ('$dora_report') = '2023' THEN\n\t\t\tCASE\n\t\t\t\tWHEN median_change_lead_time < 24 * 60 THEN CONCAT(round(median_change_lead_time/60,1), \"(elite)\")\n\t\t\t\tWHEN median_change_lead_time < 7 * 24 * 60 THEN CONCAT(round(median_change_lead_time/60,1), \"(high)\")\n\t\t\t\tWHEN median_change_lead_time < 30 * 24 * 60 THEN CONCAT(round(median_change_lead_time/60,1), \"(medium)\")\n\t\t\t\tWHEN median_change_lead_time >= 30 * 24 * 60 THEN CONCAT(round(median_change_lead_time/60,1), \"(low)\")\n\t\t\t\tELSE \"N/A. Please check if you have collected deployments/pull_requests.\"\n\t\t\t\tEND\n    WHEN ('$dora_report') = '2021' THEN\n\t\t  CASE\n\t\t\t\tWHEN median_change_lead_time < 60 THEN CONCAT(round(median_change_lead_time/60,1), \"(elite)\")\n\t\t\t\tWHEN median_change_lead_time < 7 * 24 * 60 THEN CONCAT(round(median_change_lead_time/60,1), \"(high)\")\n\t\t\t\tWHEN median_change_lead_time < 180 * 24 * 60 THEN CONCAT(round(median_change_lead_time/60,1), \"(medium)\")\n\t\t\t\tWHEN median_change_lead_time >= 180 * 24 * 60 THEN CONCAT(round(median_change_lead_time/60,1), \"(low)\")\n\t\t\t\tELSE \"N/A. Please check if you have collected deployments/pull_requests.\"\n\t\t\t\tEND\n\t\tELSE 'Invalid dora report'\n\tEND AS median_change_lead_time\nFROM _median_change_lead_time"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "stat",
   "description": "The percentage of changes that were made to a code that then resulted in incidents, rollbacks, or any type of production failure.\n\n# 2023 Benchmarks\n- **Elite**: (0, 5%]\n- **High**: (5%, 10%]\n- **Medium**: (10%, 15%]\n- **Low**: (15%, 100%]\n# 2021 Benchmarks\n- **Elite**: (0, 15%]\n- **High**: (16%, 20%]\n- **Medium**: (21%, 30%]\n- **Low**: (30%, 100%]\n",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Metric 3: change failure rate\nwith _deployments as (\n  -- When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date.\n  SELECT\n    cdc.cicd_deployment_id as deployment_id,\n    max(cdc.finished_date) as deployment_finished_date\n  FROM\n    cicd_deployment_commits cdc\n    JOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id\n    and pm.`table` = 'cicd_scopes'\n  WHERE\n    pm.project_name in (${project})\n    and cdc.result = 'SUCCESS'\n    and cdc.environment = 'PRODUCTION'\n  GROUP BY\n    1\n  HAVING\n    $__timeFilter(max(cdc.finished_date))\n),\n_failure_caused_by_deployments as (\n  -- calculate the number of incidents caused by each deployment\n  SELECT\n    d.deployment_id,\n    d.deployment_finished_date,\n    count(\n      distinct case\n        when i.id is not null then d.deployment_id\n        else null\n      end\n    ) as has_incident\n  FROM\n    _deployments d\n    left join project_incident_deployment_relationships pim on d.deployment_id = pim.deployment_id\n    left join incidents i on pim.id = i.id\n  GROUP BY\n    1,\n    2\n),\n_change_failure_rate as (\n  SELECT\n    case\n      when count(deployment_id) is null then null\n      else sum(has_incident) / count(deployment_id)\n    end as change_failure_rate\n  FROM\n    _failure_caused_by_deployments\n),\n_is_collected_data as(\n  SELECT\n    CASE\n      WHEN COUNT(i.id) = 0\n      AND COUNT(cdc.id) = 0 THEN 'No All'\n      WHEN COUNT(i.id) = 0 THEN 'No Incidents'\n      WHEN COUNT(cdc.id) = 0 THEN 'No Deployments'\n    END AS is_collected\n  FROM\n    (\n      SELECT\n        1\n    ) AS dummy\n    LEFT JOIN incidents i ON 1 = 1\n    LEFT JOIN cicd_deployment_commits cdc ON 1 = 1\n)\nSELECT\n  CASE\n    WHEN ('$dora_report') = '2023' THEN CASE\n      WHEN is_collected = \"No All\" THEN \"N/A. Please check if you have collected deployments/incidents.\"\n      WHEN is_collected = \"No Incidents\" THEN \"N/A. Please check if you have collected incidents.\"\n      WHEN is_collected = \"No Deployments\" THEN \"N/A. Please check if you have collected deployments.\"\n      WHEN change_failure_rate <=.05 THEN CONCAT(round(change_failure_rate * 100, 1), \"%(elite)\")\n      WHEN change_failure_rate <=.10 THEN CONCAT(round(change_failure_rate * 100, 1), \"%(high)\")\n      WHEN change_failure_rate <=.15 THEN CONCAT(round(change_failure_rate * 100, 1), \"%(medium)\")\n      WHEN change_failure_rate >.15 THEN CONCAT(round(change_failure_rate * 100, 1), \"%(low)\")\n      ELSE \"N/A. Please check if you have collected deployments/incidents.\"\n    END\n    WHEN ('$dora_report') = '2021' THEN CASE\n      WHEN is_collected = \"No All\" THEN \"N/A. Please check if you have collected deployments/incidents.\"\n      WHEN is_collected = \"No Incidents\" THEN \"N/A. Please check if you have collected incidents.\"\n      WHEN is_collected = \"No Deployments\" THEN \"N/A. Please check if you have collected deployments.\"\n      WHEN change_failure_rate <=.15 THEN CONCAT(round(change_failure_rate * 100, 1), \"%(elite)\")\n      WHEN change_failure_rate <=.20 THEN CONCAT(round(change_failure_rate * 100, 1), \"%(high)\")\n      WHEN change_failure_rate <=.30 THEN CONCAT(round(change_failure_rate * 100, 1), \"%(medium)\")\n      WHEN change_failure_rate >.30 THEN CONCAT(round(change_failure_rate * 100, 1), \"%(low)\")\n      ELSE \"N/A. Please check if you have collected deployments/incidents.\"\n    END\n    ELSE 'No data'\n  END AS change_failure_rate\nFROM\n  _change_failure_rate,\n  _is_collected_data"
    }
   ]
  },
  {
   "title": "${title_value} In Hours",
   "type": "stat",
   "description": "# MTTR benchmarks:\ndevlake.apache.org/docs/Metrics/MTTR#how-is-it-calculated\n# FDRT benchmarks:\ndevlake.apache.org/docs/Metrics/FailedDeploymentRecoveryTime#how-is-it-calculated\n",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "--  ***** 2023 report ***** --\n--  Metric 4: Failed deployment recovery time\nwith _deployments as (\n  SELECT\n    cdc.cicd_deployment_id as deployment_id,\n    max(cdc.finished_date) as deployment_finished_date\n  FROM\n    cicd_deployment_commits cdc\n    JOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id\n    and pm.`table` = 'cicd_scopes'\n  WHERE\n    pm.project_name in ($project)\n    and cdc.result = 'SUCCESS'\n    and cdc.environment = 'PRODUCTION'\n  GROUP BY\n    1\n  HAVING\n    $__timeFilter(max(cdc.finished_date))\n),\n_incidents_for_deployments as (\n  SELECT\n    i.id as incident_id,\n    i.created_date as incident_create_date,\n    i.resolution_date as incident_resolution_date,\n    fd.deployment_id as caused_by_deployment,\n    fd.deployment_finished_date,\n    date_format(fd.deployment_finished_date, '%y/%m') as deployment_finished_month\n  FROM\n    incidents i\n    left join project_incident_deployment_relationships pim on i.id = pim.id\n    join _deployments fd on pim.deployment_id = fd.deployment_id\n  WHERE\n    $__timeFilter(i.resolution_date)\n),\n_recovery_time_ranks as (\n  SELECT\n    *,\n    percent_rank() over(\n      order by\n        TIMESTAMPDIFF(\n          MINUTE,\n          deployment_finished_date,\n          incident_resolution_date\n        )\n    ) as ranks\n  FROM\n    _incidents_for_deployments\n),\n_median_recovery_time as (\n  SELECT\n    max(\n      TIMESTAMPDIFF(\n        MINUTE,\n        deployment_finished_date,\n        incident_resolution_date\n      )\n    ) as median_recovery_time\n  FROM\n    _recovery_time_ranks\n  WHERE\n    ranks <= 0.5\n),\n\n_is_collected_data as(\n  SELECT\n    CASE\n      WHEN EXISTS(select COUNT(d.deployment_id) from _deployments) = 0 AND EXISTS(select COUNT(i.incident_id) FROM incidents) = 0 THEN 'No deployments and incidents'\n      WHEN EXISTS(select COUNT(d.deployment_id) from _deployments) = 0 THEN 'No Deployments'\n      WHEN EXISTS(select COUNT(i.incident_id) FROM incidents) = 0 THEN 'No Incidents'\n      Else 'No incidents are mapped to deployments'\n    END AS is_collected\n  FROM\n    _deployments d, _incidents_for_deployments i\n),\n\n_metric_recovery_time_2023_report as(\n  SELECT\n    CASE\n      WHEN ('$dora_report') = '2023' THEN CASE\n        WHEN is_collected = \"No deployments and incidents\" THEN \"N/A. Please check if you have collected deployments and incidents.\"\n        WHEN is_collected = \"No Deployments\" THEN \"N/A. Please check if you have collected deployments.\"\n        WHEN is_collected = \"No Incidents\" THEN \"N/A. Please check if you have collected incidents.\"\n        WHEN median_recovery_time < 60 THEN CONCAT(round(median_recovery_time / 60, 1), \"(elite)\")\n        WHEN median_recovery_time < 24 * 60 THEN CONCAT(round(median_recovery_time / 60, 1), \"(high)\")\n        WHEN median_recovery_time < 7 * 24 * 60 THEN CONCAT(round(median_recovery_time / 60, 1), \"(medium)\")\n        WHEN median_recovery_time >= 7 * 24 * 60 THEN CONCAT(round(median_recovery_time / 60, 1), \"(low)\")\n        ELSE \"No data\"\n      END\n    END AS median_recovery_time\n  FROM\n    _median_recovery_time,\n    _is_collected_data\n),\n--  ***** 2021 report ***** --\n-- Metric 4: Median time to restore service \n_incidents as (\n  -- get the incidents created within the selected time period in the top-right corner\n  SELECT\n    distinct i.id,\n    cast(lead_time_minutes as signed) as lead_time_minutes\n  FROM\n    incidents i\n    join project_mapping pm on i.scope_id = pm.row_id\n    and pm.`table` = i.`table`\n  WHERE\n    pm.project_name in (${project})\n    and $__timeFilter(i.resolution_date)\n),\n_median_mttr_ranks as(\n  SELECT\n    *,\n    percent_rank() over(\n      order by\n        lead_time_minutes\n    ) as ranks\n  FROM\n    _incidents\n),\n_median_mttr as(\n  SELECT\n    max(lead_time_minutes) as median_time_to_resolve\n  FROM\n    _median_mttr_ranks\n  WHERE\n    ranks <= 0.5\n),\n_metric_mttr_2021_report as(\n  SELECT\n    CASE\n      WHEN ('$dora_report') = '2021' THEN CASE\n        WHEN median_time_to_resolve < 60 THEN CONCAT(round(median_time_to_resolve / 60, 1), \"(elite)\")\n        WHEN median_time_to_resolve < 24 * 60 THEN CONCAT(round(median_time_to_resolve / 60, 1), \"(high)\")\n        WHEN median_time_to_resolve < 7 * 24 * 60 THEN CONCAT(\n          round(median_time_to_resolve / 60, 1),\n          \"(medium)\"\n        )\n        WHEN median_time_to_resolve >= 7 * 24 * 60 THEN CONCAT(round(median_time_to_resolve / 60, 1), \"(low)\")\n        ELSE \"N/A. Please check if you have collected incidents.\"\n      END\n    END AS median_time_to_resolve\n  FROM\n    _median_mttr\n)\nSELECT\n  median_recovery_time AS median_time_in_hour\nFROM\n  _metric_recovery_time_2023_report\nWHERE\n  ('$dora_report') = '2023'\nUNION\nSELECT\n  median_time_to_resolve AS median_time_to_resolve\nFROM\n  _metric_mttr_2021_report\nWHERE\n  ('$dora_report') = '2021'"
    }
   ]
  },
  {
   "title": "Monthly deployments",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "-- Metric 1: Number of deployments per month\nwith _deployments as(\n-- When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date.\n\tSELECT \n\t\tdate_format(deployment_finished_date,'%y/%m') as month,\n\t\tcount(cicd_deployment_id) as deployment_count\n\tFROM (\n\t\tSELECT\n\t\t\tcdc.cicd_deployment_id,\n\t\t\tmax(cdc.finished_date) as deployment_finished_date\n\t\tFROM cicd_deployment_commits cdc\n\t\tJOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id and pm.`table` = 'cicd_scopes'\n\t\tWHERE\n\t\t\tpm.project_name in (${project})\n\t\t\tand cdc.result = 'SUCCESS'\n\t\t\tand cdc.environment = 'PRODUCTION'\n\t\tGROUP BY 1\n\t\tHAVING $__timeFilter(max(cdc.finished_date))\n\t) _production_deployments\n\tGROUP BY 1\n)\n\nSELECT \n\tcm.month, \n\tcase when d.deployment_count is null then 0 else d.deployment_count end as 'Deployment Count'\nFROM \n\tcalendar_months cm\n\tLEFT JOIN _deployments d on cm.month = d.month\n\tWHERE month_timestamp between DATE(DATE_FORMAT($__timeFrom(), '%Y-%m-01')) AND DATE(DATE_FORMAT($__timeTo(), '%Y-%m-01'))"
    }
   ]
  },
  {
   "title": "Median Lead Time for Changes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "-- Metric 2: median change lead time per month\nwith _pr_stats as (\n-- get the cycle time of PRs deployed by the deployments finished each month\n\tSELECT\n\t\tdistinct pr.id,\n\t\tdate_format(cdc.finished_date,'%y/%m') as month,\n\t\tppm.pr_cycle_time\n\tFROM\n\t\tpull_requests pr\n\t\tjoin project_pr_metrics ppm on ppm.id = pr.id\n\t\tjoin project_mapping pm on pr.base_repo_id = pm.row_id and pm.`table` = 'repos'\n\t\tjoin cicd_deployment_commits cdc on ppm.deployment_commit_id = cdc.id\n\tWHERE\n\t\tpm.project_name in (${project}) \n\t\tand pr.merged_date is not null\n\t\tand ppm.pr_cycle_time is not null\n\t\tand $__timeFilter(cdc.finished_date)\n),\n\n_find_median_clt_each_month_ranks as(\n\tSELECT *, percent_rank() over(PARTITION BY month order by pr_cycle_time) as ranks\n\tFROM _pr_stats\n),\n\n_clt as(\n\tSELECT month, max(pr_cycle_time) as median_change_lead_time\n\tFROM _find_median_clt_each_month_ranks\n\tWHERE ranks <= 0.5\n\tgroup by month\n)\n\nSELECT \n\tcm.month,\n\tcase \n\t\twhen _clt.median_change_lead_time is null then 0 \n\t\telse _clt.median_change_lead_time/60 end as 'Median Change Lead Time In Hours'\nFROM \n\tcalendar_months cm\n\tLEFT JOIN _clt on cm.month = _clt.month\n  WHERE month_timestamp between DATE(DATE_FORMAT($__timeFrom(), '%Y-%m-01')) AND DATE(DATE_FORMAT($__timeTo(), '%Y-%m-01'))"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "-- Metric 3: change failure rate per month\nwith _deployments as (\n  -- When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date.\n  SELECT\n    cdc.cicd_deployment_id as deployment_id,\n    max(cdc.finished_date) as deployment_finished_date\n  FROM\n    cicd_deployment_commits cdc\n    JOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id\n    and pm.`table` = 'cicd_scopes'\n  WHERE\n    pm.project_name in (${project})\n    and cdc.result = 'SUCCESS'\n    and cdc.environment = 'PRODUCTION'\n  GROUP BY\n    1\n  HAVING\n    $__timeFilter(max(cdc.finished_date))\n),\n_failure_caused_by_deployments as (\n  -- calculate the number of incidents caused by each deployment\n  SELECT\n    d.deployment_id,\n    d.deployment_finished_date,\n    count(\n      distinct case\n        when i.id is not null then d.deployment_id\n        else null\n      end\n    ) as has_incident\n  FROM\n    _deployments d\n    left join project_incident_deployment_relationships pim on d.deployment_id = pim.deployment_id\n    left join incidents i on pim.id = i.id\n  GROUP BY\n    1,\n    2\n),\n_change_failure_rate_for_each_month as (\n  SELECT\n    date_format(deployment_finished_date, '%y/%m') as month,\n    case\n      when count(deployment_id) is null then null\n      else sum(has_incident) / count(deployment_id)\n    end as change_failure_rate\n  FROM\n    _failure_caused_by_deployments\n  GROUP BY\n    1\n)\nSELECT\n  cm.month,\n  cfr.change_failure_rate as 'Change Failure Rate'\nFROM\n  calendar_months cm\n  LEFT JOIN _change_failure_rate_for_each_month cfr on cm.month = cfr.month\nWHERE\n  month_timestamp between DATE(DATE_FORMAT($__timeFrom(), '%Y-%m-01')) AND DATE(DATE_FORMAT($__timeTo(), '%Y-%m-01'))"
    }
   ]
  },
  {
   "title": "${title_value}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "--  ***** 2023 report ***** --\n--  Metric 4: Failed deployment recovery time\nwith _deployments as (\n  SELECT\n    cdc.cicd_deployment_id as deployment_id,\n    max(cdc.finished_date) as deployment_finished_date\n  FROM\n    cicd_deployment_commits cdc\n    JOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id\n    and pm.`table` = 'cicd_scopes'\n  WHERE\n    pm.project_name in ($project)\n    and cdc.result = 'SUCCESS'\n    and cdc.environment = 'PRODUCTION'\n  GROUP BY\n    1\n  HAVING\n    $__timeFilter(max(cdc.finished_date))\n),\n_incidents_for_deployments as (\n  SELECT\n    i.id as incident_id,\n    i.created_date as incident_create_date,\n    i.resolution_date as incident_resolution_date,\n    fd.deployment_id as caused_by_deployment,\n    fd.deployment_finished_date,\n    date_format(fd.deployment_finished_date, '%y/%m') as deployment_finished_month\n  FROM\n    incidents i\n    left join project_incident_deployment_relationships pim on i.id = pim.id\n    join _deployments fd on pim.deployment_id = fd.deployment_id\n  WHERE\n    $__timeFilter(i.resolution_date)\n),\n_recovery_time_ranks as (\n  SELECT\n    *,\n    percent_rank() over(\n      PARTITION BY deployment_finished_month\n      order by\n        TIMESTAMPDIFF(\n          MINUTE,\n          deployment_finished_date,\n          incident_resolution_date\n        )\n    ) as ranks\n  FROM\n    _incidents_for_deployments\n),\n_median_recovery_time as (\n  SELECT\n    deployment_finished_month,\n    max(\n      TIMESTAMPDIFF(\n        MINUTE,\n        deployment_finished_date,\n        incident_resolution_date\n      )\n    ) as median_recovery_time\n  FROM\n    _recovery_time_ranks\n  WHERE\n    ranks <= 0.5\n  GROUP BY\n    deployment_finished_month\n),\n_metric_recovery_time_2023_report as (\n  SELECT\n    cm.month,\n    case\n      when m.median_recovery_time is null then 0\n      else m.median_recovery_time / 60\n    end as median_recovery_time_in_hour\n  FROM\n    calendar_months cm\n    LEFT JOIN _median_recovery_time m on cm.month = m.deployment_finished_month\n  WHERE\n    month_timestamp between DATE(DATE_FORMAT($__timeFrom(), '%Y-%m-01')) AND DATE(DATE_FORMAT($__timeTo(), '%Y-%m-01'))\n),\n--  ***** 2021 report ***** --\n-- Metric 4: median time to restore service - MTTR\n_incidents as (\n  -- get the number of incidents created each month\n  SELECT\n    distinct i.id,\n    date_format(i.resolution_date, '%y/%m') as month,\n    cast(lead_time_minutes as signed) as lead_time_minutes\n  FROM\n    incidents i\n    join project_mapping pm on i.scope_id = pm.row_id\n    and pm.`table` = i.`table`\n  WHERE\n    pm.project_name in (${project})\n    and i.lead_time_minutes is not null\n),\n_find_median_mttr_each_month_ranks as(\n  SELECT\n    *,\n    percent_rank() over(\n      PARTITION BY month\n      order by\n        lead_time_minutes\n    ) as ranks\n  FROM\n    _incidents\n),\n_mttr as(\n  SELECT\n    month,\n    max(lead_time_minutes) as median_time_to_resolve\n  FROM\n    _find_median_mttr_each_month_ranks\n  WHERE\n    ranks <= 0.5\n  GROUP BY\n    month\n),\n_metric_mttr_2021_report as (\n  SELECT\n    cm.month,\n    case\n      when m.median_time_to_resolve is null then 0\n      else m.median_time_to_resolve / 60\n    end as median_time_to_resolve_in_hour\n  FROM\n    calendar_months cm\n    LEFT JOIN _mttr m on cm.month = m.month\n  WHERE\n    month_timestamp between DATE(DATE_FORMAT($__timeFrom(), '%Y-%m-01')) AND DATE(DATE_FORMAT($__timeTo(), '%Y-%m-01'))\n)\nSELECT\n  cm.month,\n  CASE\n    WHEN '${dora_report}' = '2023' THEN mrt.median_recovery_time_in_hour\n    WHEN '${dora_report}' = '2021' THEN mm.median_time_to_resolve_in_hour\n  END AS '${title_value} In Hours'\nFROM\n  calendar_months cm\n  LEFT JOIN _metric_recovery_time_2023_report mrt ON cm.month = mrt.month\n  LEFT JOIN _metric_mttr_2021_report mm ON cm.month = mm.month\nWHERE\n  month_timestamp between DATE(DATE_FORMAT($__timeFrom(), '%Y-%m-01')) AND DATE(DATE_FORMAT($__timeTo(), '%Y-%m-01'))"
    }
   ]
  }
 ]
}