/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package mocks holds the mockery-generated mocks for
// github.com/apache/devlake/helpers/pluginhelper/api.
//
// Only this file is tracked. The mocks themselves are generated by
// `make mock` and git-ignored; this placeholder keeps the import path
// resolvable inside the main module, so that `go mod tidy` works on a
// fresh clone.
package mocks
