{
 "title": "Bitbucket (PostgreSQL)",
 "tags": [
  "Data Source Dashboard",
  "Stable Data Sources"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repo_id",
    "label": "Repo",
    "query": "select concat(name, '--', id) as text from repos where id like 'bitbucket%'"
   },
   {
    "name": "interval",
    "label": "Time Interval",
    "query": "Month : DAYOFMONTH, Week : WEEKDAY"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard shows the basic Git and Code Review metrics from Bitbucket.\n- Data Source Required: Bitbucket Cloud or Server/data center. Please note that for Bitbucket Server/Data center, there is no embedded CI/CD data."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "1. Contribution (PRs)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "1.1 Number of New Pull Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT pr.id) AS pull_request_count FROM pull_requests AS pr WHERE $__timeFilter(created_date) AND base_repo_id = ANY(ARRAY[${repo_id}]::text[])"
    }
   ]
  },
  {
   "title": "1.2 Number of New Pull Requests",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 4 },
   "targets": [
    {
     "rawSql": "WITH _prs AS (SELECT CAST(created_date AS DATE) + INTERVAL '1 day' AS time, COUNT(DISTINCT id) AS pr_count FROM pull_requests WHERE base_repo_id = ANY(ARRAY[${repo_id}]::text[]) AND $__timeFilter(created_date) AND created_date >= $__timeFrom()::timestamp + INTERVAL '1 day' + INTERVAL '1 MONTH' GROUP BY 1) SELECT CASE WHEN '$interval' = 'DAYOFMONTH' THEN TO_CHAR(time, '%M %Y') ELSE CONCAT('W', TO_CHAR(time, '%u %Y')) END AS _time, pr_count AS \"Pull Request Count\" FROM _prs ORDER BY time NULLS FIRST"
    }
   ]
  },
  {
   "title": "1.3 Top 20 Contributors By Merged PRs",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "select": [
      [
       { "params": [ "id" ], "type": "column" }
      ]
     ],
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "ae_projects",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "2. How PRs are handled?",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "2.1 Ratio of unmerged Pull Requests of All Closed or Merged PRs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "select": [
      [
       { "params": [ "id" ], "type": "column" }
      ]
     ],
     "table": "ae_projects",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "2.2 Pull Request Status Distribution",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 17 },
   "targets": [
    {
     "select": [
      [
       { "params": [ "id" ], "type": "column" }
      ]
     ],
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "ae_projects",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "2.3 Number of Pull Requests Closed without Merging [Selected Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "select": [
      [
       { "params": [ "id" ], "type": "column" }
      ]
     ],
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "ae_projects",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "2.4 Ratio of Non-merging PRs of All Closed or Merged PRs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "select": [
      [
       { "params": [ "id" ], "type": "column" }
      ]
     ],
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "ae_projects",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "2.5 Mean Time to Merge of Pull Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(CAST((EXTRACT(EPOCH FROM (merged_date - created_date))/60) AS NUMERIC) / NULLIF(1440, 0)) FROM pull_requests WHERE $__timeFilter(created_date) AND base_repo_id = ANY(ARRAY[${repo_id}]::text[]) AND NOT merged_date IS NULL"
    }
   ]
  },
  {
   "title": "2.6 Mean Time to Merge of Pull Requests",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "rawSql": "WITH _prs AS (SELECT CAST(created_date AS DATE) + INTERVAL '1 day' AS time, AVG(CAST((EXTRACT(EPOCH FROM (merged_date - created_date))/60) AS NUMERIC) / NULLIF(1440, 0)) AS time_to_merge FROM pull_requests WHERE $__timeFilter(created_date) AND base_repo_id = ANY(ARRAY[${repo_id}]::text[]) AND created_date >= $__timeFrom()::timestamp + INTERVAL '1 day' + INTERVAL '1 MONTH' GROUP BY 1) SELECT CASE WHEN '$interval' = 'DAYOFMONTH' THEN TO_CHAR(time, '%M %Y') ELSE CONCAT('W', TO_CHAR(time, '%u %Y')) END AS _time, time_to_merge AS \"Time to Merge\" FROM _prs ORDER BY time NULLS FIRST"
    }
   ]
  },
  { "title": "CI/CD Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "3.1 Number of successful pipeline runs",
   "type": "stat",
   "description": "Number of pipeline runs executed in the selected time range",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT id) FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND result = 'SUCCESS' AND id LIKE \"bitbucket%\" AND cicd_scope_id = ANY(ARRAY[${repo_id}]::text[]) /* Enable the following condition to remove the month with incomplete data */ /* and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH) */"
    }
   ]
  },
  {
   "title": "3.2 Mean pipeline run success rate %",
   "type": "stat",
   "description": "Number of successful pipeline runs / Number of total pipeline runs",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(1.0 * COUNT(CASE WHEN result = 'SUCCESS' THEN id ELSE NULL END) AS NUMERIC) / NULLIF(COUNT(DISTINCT id), 0) FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND id LIKE \"bitbucket%\" AND cicd_scope_id = ANY(ARRAY[${repo_id}]::text[]) AND /* Enable the following condition to remove the month with incomplete data */ finished_date >= $__timeFrom()::timestamp + INTERVAL '1 day' + INTERVAL '1 MONTH'"
    }
   ]
  },
  {
   "title": "3.3 Number of successful and failed pipeline runs",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "rawSql": "WITH _builds AS (SELECT CAST(finished_date AS DATE) + INTERVAL '1 day' AS time, COUNT(DISTINCT CASE WHEN result = 'SUCCESS' THEN id ELSE NULL END) AS successful_count, COUNT(DISTINCT CASE WHEN result <> 'SUCCESS' THEN id ELSE NULL END) AS failed_count FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND id LIKE \"bitbucket%\" AND cicd_scope_id = ANY(ARRAY[${repo_id}]::text[]) GROUP BY 1) SELECT CASE WHEN '$interval' = 'DAYOFMONTH' THEN TO_CHAR(time, '%M %Y') ELSE CONCAT('W', TO_CHAR(time, '%u %Y')) END AS _time, successful_count, failed_count FROM _builds ORDER BY time NULLS FIRST"
    }
   ]
  },
  {
   "title": "3.4 Pipeline runs result distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT CASE WHEN result = '' THEN 'Unknown' ELSE result END AS result, COUNT(DISTINCT id) AS build_count FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND id LIKE \"bitbucket%\" AND cicd_scope_id = ANY(ARRAY[${repo_id}]::text[]) GROUP BY 1 ORDER BY 2 DESC NULLS LAST"
    }
   ]
  },
  {
   "title": "3.5 Pipeline run success rate %",
   "type": "barchart",
   "description": "1. Mean Pipeline Runs success rate over time.\n2. The Pipeline runs being calculated are filtered by \"workflow runs starting time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH _build_success_rate AS (SELECT CAST(finished_date AS DATE) + INTERVAL '1 day' AS time, result, id FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND id LIKE \"bitbucket%\" AND cicd_scope_id = ANY(ARRAY[${repo_id}]::text[]) GROUP BY time, result, id) SELECT CASE WHEN '$interval' = 'DAYOFMONTH' THEN TO_CHAR(time, '%m/%Y') ELSE CONCAT('W', TO_CHAR(time, '%u %Y')) END AS _time, CAST(1.0 * SUM(CASE WHEN result = 'SUCCESS' THEN 1 ELSE 0 END) AS NUMERIC) / NULLIF(COUNT(*), 0) AS \"Pipeline Runs Success Rate\" FROM _build_success_rate GROUP BY time ORDER BY time NULLS FIRST"
    }
   ]
  },
  {
   "title": "3.6 Mean pipeline runs duration",
   "type": "stat",
   "description": "Number of successful pipeline runs / Number of total pipeline runs",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT AVG(CAST(duration_sec AS NUMERIC) / NULLIF(60, 0)) AS duration_in_minutes FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND id LIKE \"bitbucket%\" AND cicd_scope_id = ANY(ARRAY[${repo_id}]::text[]) AND /* Enable the following condition to remove the month with incomplete data */ finished_date >= $__timeFrom()::timestamp + INTERVAL '1 day' + INTERVAL '1 MONTH'"
    }
   ]
  },
  {
   "title": "3.7 Mean pipeline run duration",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH _builds AS (SELECT CAST(finished_date AS DATE) + INTERVAL '1 day' AS time, AVG(duration_sec) AS mean_duration_sec FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND id LIKE \"bitbucket%\" AND cicd_scope_id = ANY(ARRAY[${repo_id}]::text[]) GROUP BY 1) SELECT CASE WHEN '$interval' = 'DAYOFMONTH' THEN TO_CHAR(time, '%M %Y') ELSE CONCAT('W', TO_CHAR(time, '%u %Y')) END AS _time, mean_duration_sec FROM _builds ORDER BY time NULLS FIRST"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 54 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   },
   "targets": [
    {}
   ]
  }
 ]
}