{
 "title": "CircleCI (PostgreSQL)",
 "tags": [
  "Data Source Dashboard",
  "Stable Data Sources"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "full_name",
    "label": "CircleCI Project",
    "query": "select concat(name, '--', id) as text from cicd_scopes where id like \"%circleci%\" "
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard shows the basic CI/CD metrics from CircleCI, such as [Build Count](https://devlake.apache.org/docs/Metrics/BuildCount), [Build Duration](https://devlake.apache.org/docs/Metrics/BuildDuration) and [Build Success Rate](https://devlake.apache.org/docs/Metrics/BuildSuccessRate).\n- Data Source Required: CircleCI"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "1. Total Number of Successful Workflows [Selected Time Range]",
   "type": "stat",
   "description": "Number of builds executed in the selected time range",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT id) FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND result = 'SUCCESS' AND id LIKE '%circleci%' AND cicd_scope_id = ANY(ARRAY[${full_name}]::text[])"
    }
   ]
  },
  {
   "title": "2. Mean Workflow Success Rate",
   "type": "stat",
   "description": "Number of successful workflows / Number of total workflows",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(1.0 * COUNT(CASE WHEN result = 'SUCCESS' THEN id ELSE NULL END) AS NUMERIC) / NULLIF(COUNT(DISTINCT id), 0) FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND id LIKE '%circleci%' AND cicd_scope_id = ANY(ARRAY[${full_name}]::text[])"
    }
   ]
  },
  {
   "title": "3. Total Workflow Result Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT result, COUNT(DISTINCT id) AS build_count FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND id LIKE '%circleci%' AND cicd_scope_id = ANY(ARRAY[${full_name}]::text[]) GROUP BY 1 ORDER BY 2 DESC NULLS LAST"
    }
   ]
  },
  {
   "title": "4. Mean Workflow Duration in Minutes",
   "type": "stat",
   "description": "Number of successful workflows / Number of total workflows",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT AVG(CAST(duration_sec AS NUMERIC) / NULLIF(60, 0)) AS duration_in_minutes FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND id LIKE '%circleci%' AND cicd_scope_id = ANY(ARRAY[${full_name}]::text[])"
    }
   ]
  },
  {
   "title": "1.1 Total Number of Successful Workflows [Each Month]",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH _builds AS (SELECT CAST(finished_date AS DATE) + INTERVAL '1 day' AS time, COUNT(DISTINCT id) AS build_count FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND result = 'SUCCESS' AND id LIKE '%circleci%' AND cicd_scope_id = ANY(ARRAY[${full_name}]::text[]) GROUP BY 1) SELECT TO_CHAR(time, '%M %Y') AS month, build_count AS \"Workflow Count\" FROM _builds ORDER BY time NULLS FIRST"
    }
   ]
  },
  {
   "title": "2.1 Workflow Success Rate [Each Month]",
   "type": "barchart",
   "description": "1. Mean workflows success rate over time.\n2. The workflows being calculated are filtered by \"build starting time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH _build_success_rate AS (SELECT CAST(finished_date AS DATE) + INTERVAL '1 day' AS time, result, id FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND id LIKE '%circleci%' AND cicd_scope_id = ANY(ARRAY[${full_name}]::text[]) GROUP BY time, result, id) SELECT TO_CHAR(time, '%M %Y') AS month, CAST(1.0 * SUM(CASE WHEN result = 'SUCCESS' THEN 1 ELSE 0 END) AS NUMERIC) / NULLIF(COUNT(*), 0) AS \"Workflow Success Rate\" FROM _build_success_rate GROUP BY 1 ORDER BY 1 NULLS FIRST"
    }
   ]
  },
  {
   "title": "3.1 Number of Successful and Failed Workflows [Each Month]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT CAST(finished_date AS DATE) + INTERVAL '1 day' AS time, COUNT(DISTINCT CASE WHEN result = 'SUCCESS' THEN id ELSE NULL END) AS successful_workflow_count, COUNT(DISTINCT CASE WHEN result <> 'SUCCESS' THEN id ELSE NULL END) AS failed_workflow_count FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND id LIKE '%circleci%' AND cicd_scope_id = ANY(ARRAY[${full_name}]::text[]) GROUP BY 1"
    }
   ]
  },
  {
   "title": "4.1 Mean Workflow Duration in Minutes [Each Month]",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "WITH _builds AS (SELECT CAST(finished_date AS DATE) + INTERVAL '1 day' AS time, AVG(duration_sec) AS mean_duration_sec FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND id LIKE '%circleci%' AND cicd_scope_id = ANY(ARRAY[${full_name}]::text[]) GROUP BY 1) SELECT TO_CHAR(time, '%M %Y') AS month, CAST(mean_duration_sec AS NUMERIC) / NULLIF(60, 0) AS mean_duration_minutes FROM _builds ORDER BY time NULLS FIRST"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   },
   "targets": [
    {}
   ]
  }
 ]
}