{
 "title": "Component and File-level Metrics (PostgreSQL)",
 "description": "This dashboard shows the metrics  collected by gitextractor plugin",
 "tags": [ "Engineering Leads Dashboard" ],
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repo_id",
    "label": "Repo",
    "query": "select concat(name, '--', id) as text from repos"
   },
   { "name": "selected_path", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Author dimension",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "commits distribution by author",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT author_name, COUNT(DISTINCT commit_sha) AS commit_nums FROM commits, repo_commits WHERE commits.sha = repo_commits.commit_sha AND repo_commits.repo_id = ANY(ARRAY[${repo_id}]::text[]) AND $__timeFilter(commits.authored_date) GROUP BY author_name, author_id ORDER BY commit_nums DESC NULLS LAST LIMIT 10"
    }
   ]
  },
  {
   "title": "lines of code distribution by author",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT author_name, SUM(additions - deletions) AS cnt FROM commits, repo_commits WHERE commits.sha = repo_commits.commit_sha AND repo_commits.repo_id = ANY(ARRAY[${repo_id}]::text[]) AND $__timeFilter(commits.authored_date) GROUP BY author_name, author_id ORDER BY cnt DESC NULLS LAST LIMIT 10"
    }
   ]
  },
  {
   "title": "Time dimension",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "commits distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT CASE CAST(EXTRACT(ISODOW FROM CAST(authored_date AS DATE)) AS TEXT) WHEN '2' THEN '1.Monday' WHEN '3' THEN '2.Tuesday' WHEN '4' THEN '3.Wednesday' WHEN '5' THEN '4.Thursday' WHEN '6' THEN '5.Friday' WHEN '7' THEN '6.Saturday' WHEN '1' THEN '7.Sunday' END AS weekday, COUNT(DISTINCT commit_sha) AS commit_nums FROM commits, repo_commits WHERE $__timeFilter(commits.authored_date) AND commits.sha = repo_commits.commit_sha AND repo_commits.repo_id = ANY(ARRAY[${repo_id}]::text[]) GROUP BY weekday"
    }
   ]
  },
  {
   "title": "lines of code distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT CASE CAST(EXTRACT(ISODOW FROM CAST(authored_date AS DATE)) AS TEXT) WHEN '2' THEN '1.Monday' WHEN '3' THEN '2.Tuesday' WHEN '4' THEN '3.Wednesday' WHEN '5' THEN '4.Thursday' WHEN '6' THEN '5.Friday' WHEN '7' THEN '6.Saturday' WHEN '1' THEN '7.Sunday' END AS weekday, SUM(additions - deletions) AS changed_nums, SUM(additions) AS total_additions, SUM(deletions) AS total_deletions FROM commits, repo_commits WHERE commits.sha = repo_commits.commit_sha AND repo_commits.repo_id = ANY(ARRAY[${repo_id}]::text[]) AND $__timeFilter(commits.authored_date) GROUP BY weekday ORDER BY weekday NULLS FIRST"
    }
   ]
  },
  {
   "title": "File dimension",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Files with maximum number of authors",
   "type": "barchart",
   "description": "Please disable the SkipCommitFiles in the .env setting to view this metric. However, this will significantly increase the time to collect data.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT file_path, COUNT(DISTINCT c.author_name) AS cnt FROM commits AS c JOIN commit_files AS cf ON cf.commit_sha = c.sha JOIN repo_commits AS rc ON cf.commit_sha = rc.commit_sha WHERE repo_id = ANY(ARRAY[${repo_id}]::text[]) AND $__timeFilter(c.authored_date) AND CAST(file_path AS TEXT) ~ '${selected_path:raw}' GROUP BY file_path ORDER BY cnt DESC NULLS LAST LIMIT 10"
    }
   ]
  },
  {
   "title": "[Selected Files] Largest files with lowest number of authors",
   "type": "table",
   "description": "Please disable the SkipCommitFiles in the .env setting to view this metric. However, this will significantly increase the time to collect data.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT file_path, COUNT(DISTINCT author_name) AS author_count, MAX(rst) AS lines_of_code, CAST(MAX(rst) AS NUMERIC) / NULLIF(COUNT(DISTINCT author_name), 0) AS rate FROM commits JOIN (SELECT file_path, commit_files.commit_sha, SUM(additions - deletions) AS rst FROM commit_files JOIN repo_commits AS rc ON commit_files.commit_sha = rc.commit_sha WHERE repo_id = ANY(ARRAY[${repo_id}]::text[]) AND CAST(file_path AS TEXT) ~ '${selected_path:raw}' GROUP BY file_path, commit_files.commit_sha) AS a ON a.commit_sha = commits.sha GROUP BY file_path HAVING author_count > 0 ORDER BY rate DESC NULLS LAST"
    }
   ]
  },
  {
   "title": "Files with most modifications",
   "type": "barchart",
   "description": "Please disable the SkipCommitFiles in the .env setting to view this metric. However, this will significantly increase the time to collect data.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT file_path, COUNT(DISTINCT sha) AS modified_num FROM commits AS c JOIN commit_files AS cf ON cf.commit_sha = c.sha JOIN repo_commits AS rc ON cf.commit_sha = rc.commit_sha WHERE repo_id = ANY(ARRAY[${repo_id}]::text[]) AND $__timeFilter(c.authored_date) AND CAST(file_path AS TEXT) ~ '${selected_path:raw}' GROUP BY file_path ORDER BY modified_num DESC NULLS LAST LIMIT 10"
    }
   ]
  },
  {
   "title": "[All Files] Files with most modifications",
   "type": "barchart",
   "description": "Please disable the SkipCommitFiles in the .env setting to view this metric. However, this will significantly increase the time to collect data.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT file_path, COUNT(DISTINCT sha) AS cnt FROM commits AS c JOIN commit_files AS cf ON cf.commit_sha = c.sha JOIN repo_commits AS rc ON cf.commit_sha = rc.commit_sha WHERE repo_id = ANY(ARRAY[${repo_id}]::text[]) AND $__timeFilter(c.authored_date) GROUP BY file_path ORDER BY cnt DESC NULLS LAST LIMIT 10"
    }
   ]
  },
  {
   "title": "Lineage dimension",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "In which day the code has highest chance to stay in repository.",
   "type": "barchart",
   "description": "Please disable the SkipCommitFiles in the .env setting to view this metric. However, this will significantly increase the time to collect data.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT CASE CAST(EXTRACT(ISODOW FROM CAST(commits.committed_date AS DATE)) AS TEXT) WHEN '2' THEN '1.Monday' WHEN '3' THEN '2.Tuesday' WHEN '4' THEN '3.Wednesday' WHEN '5' THEN '4.Thursday' WHEN '6' THEN '5.Friday' WHEN '7' THEN '6.Saturday' WHEN '1' THEN '7.Sunday' END AS wd, COUNT(*) AS lived_lines FROM repo_snapshot JOIN commits ON commits.sha = repo_snapshot.commit_sha WHERE repo_snapshot.repo_id = ANY(ARRAY[${repo_id}]::text[]) AND $__timeFilter(commits.committed_date) GROUP BY wd ORDER BY wd NULLS FIRST"
    }
   ]
  },
  {
   "title": "Which file has the longest average line age?",
   "type": "table",
   "description": "Please disable the SkipCommitFiles in the .env setting to view this metric. However, this will significantly increase the time to collect data.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT file_path, AVG((EXTRACT(EPOCH FROM (NOW() - commits.committed_date))/86400)) AS line_age FROM repo_snapshot JOIN commits ON repo_snapshot.commit_sha = commits.sha WHERE repo_snapshot.repo_id = ANY(ARRAY[${repo_id}]::text[]) AND $__timeFilter(commits.committed_date) GROUP BY file_path ORDER BY line_age DESC NULLS LAST LIMIT 20"
    }
   ]
  }
 ]
}