{
 "title": "Contributor Experience (PostgreSQL)",
 "tags": [ "OSS Maintainer Dashboard" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repo_id",
    "label": "Repo",
    "query": "select concat(name, '-', id) from repos"
   },
   {
    "name": "iir_sla",
    "label": "Time to Initial Issue Response SLA (in hours)",
    "query": "24"
   },
   {
    "name": "prrt_sla",
    "label": "PR Resolution Time SLA (in days)",
    "query": "7"
   },
   { "name": "label_gfi", "label": "Label for good first issues", "query": "good first issue" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard answers the question \"What makes a great developer experience? And how can we define and track that?\". This dashboard heavily focuses on actionability. All metrics can be deterministically improved as long as OSS maintainers invested time into them.\n- Data Source Required: GitHub"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Time To Initial Issue Response [Last Month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH issue_comment_list AS (SELECT i.id AS issue_id, i.url, i.title, i.created_date AS issue_created_date, ic.id AS comment_id, ic.created_date AS comment_date, ic.body, CASE WHEN NOT ic.id IS NULL THEN RANK() OVER (PARTITION BY i.id ORDER BY ic.created_date ASC NULLS FIRST) ELSE NULL END AS comment_rank FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id LEFT JOIN issue_comments AS ic ON i.id = ic.issue_id WHERE CAST(i.created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' - INTERVAL '1 MONTH' AND CURRENT_DATE - INTERVAL '1 day' AND b.id = ANY(ARRAY[${repo_id}]::text[])) SELECT AVG(CAST(((EXTRACT(EPOCH FROM (comment_date - issue_created_date))/60)) AS NUMERIC) / NULLIF(1440, 0)) FROM issue_comment_list WHERE comment_rank = 1"
    }
   ]
  },
  {
   "title": "Issue Resolution Time [Last Month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(CAST(i.lead_time_minutes AS NUMERIC) / NULLIF(1440, 0)) AS issue_lead_time FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE CAST(i.created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' - INTERVAL '1 MONTH' AND CURRENT_DATE - INTERVAL '1 day' AND i.status = 'DONE' AND b.id = ANY(ARRAY[${repo_id}]::text[])"
    }
   ]
  },
  {
   "title": "Issue Response Rate within SLA [Last Month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH issue_comment_list AS (SELECT i.id AS issue_id, i.url, i.title, i.created_date AS issue_created_date, ic.id AS comment_id, ic.created_date AS comment_date, ic.body, CASE WHEN NOT ic.id IS NULL THEN RANK() OVER (PARTITION BY i.id ORDER BY ic.created_date ASC NULLS FIRST) ELSE NULL END AS comment_rank FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id LEFT JOIN issue_comments AS ic ON i.id = ic.issue_id WHERE CAST(i.created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' - INTERVAL '1 MONTH' AND CURRENT_DATE - INTERVAL '1 day' AND b.id = ANY(ARRAY[${repo_id}]::text[])) SELECT CAST(100 * SUM(CASE WHEN CAST(((EXTRACT(EPOCH FROM (comment_date - issue_created_date))/60)) AS NUMERIC) / NULLIF(60, 0) < $iir_sla THEN 1 ELSE NULL END) AS NUMERIC) / NULLIF(COUNT(*), 0) FROM issue_comment_list WHERE comment_rank = 1"
    }
   ]
  },
  {
   "title": "Number of Good First Issues [Outstanding]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT i.id) FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN issue_labels AS il ON il.issue_id = i.id WHERE il.label_name = '$label_gfi' AND i.status <> 'DONE' AND b.id = ANY(ARRAY[${repo_id}]::text[])"
    }
   ]
  },
  {
   "title": "Time to Initial PR Review  [Last Month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH pr_comment_list AS (SELECT pr.id AS issue_id, pr.url, pr.title, pr.created_date AS pr_created_date, prc.id AS comment_id, prc.created_date AS comment_date, prc.account_id, CASE WHEN NOT prc.id IS NULL THEN RANK() OVER (PARTITION BY pr.id ORDER BY prc.created_date ASC NULLS FIRST) ELSE NULL END AS comment_rank FROM pull_requests AS pr LEFT JOIN pull_request_comments AS prc ON pr.id = prc.pull_request_id WHERE CAST(pr.created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' - INTERVAL '1 MONTH' AND CURRENT_DATE - INTERVAL '1 day' AND pr.base_repo_id = ANY(ARRAY[${repo_id}]::text[])) SELECT AVG(CAST(((EXTRACT(EPOCH FROM (comment_date - pr_created_date))/60)) AS NUMERIC) / NULLIF(1440, 0)) FROM pr_comment_list WHERE comment_rank = 1"
    }
   ]
  },
  {
   "title": "PR Resolution Time [Last Month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* The PR/MR statuses are standardized to DevLake's statuses 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field \"original_status\" */ SELECT AVG(CAST((EXTRACT(EPOCH FROM (closed_date - created_date))/60) AS NUMERIC) / NULLIF(1440, 0)) AS time_to_close FROM pull_requests AS pr WHERE CAST(created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' - INTERVAL '1 MONTH' AND CURRENT_DATE - INTERVAL '1 day' AND status IN ('CLOSED', 'MERGED') AND pr.base_repo_id = ANY(ARRAY[${repo_id}]::text[])"
    }
   ]
  },
  {
   "title": "PR Resolution Rate within SLA [Last Month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* The PR/MR statuses are standardized to DevLake's statuses 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field \"original_status\" */ SELECT CAST(100 * SUM(CASE WHEN CAST((EXTRACT(EPOCH FROM (closed_date - created_date))/60) AS NUMERIC) / NULLIF(1440, 0) < $prrt_sla THEN 1 ELSE NULL END) AS NUMERIC) / NULLIF(COUNT(*), 0) FROM pull_requests AS pr WHERE CAST(created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' - INTERVAL '1 MONTH' AND CURRENT_DATE - INTERVAL '1 day' AND status IN ('CLOSED', 'MERGED') AND pr.base_repo_id = ANY(ARRAY[${repo_id}]::text[])"
    }
   ]
  },
  {
   "title": "PR Closed W/O Merging Ratio [Last Month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* The PR/MR statuses are standardized to DevLake's statuses 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field \"original_status\" */ SELECT CAST(100 * COUNT(DISTINCT CASE WHEN status = 'CLOSED' THEN id ELSE NULL END) AS NUMERIC) / NULLIF(COUNT(DISTINCT CASE WHEN status IN ('CLOSED', 'MERGED') THEN id ELSE NULL END), 0) AS ratio FROM pull_requests AS pr WHERE CAST(created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' - INTERVAL '1 MONTH' AND CURRENT_DATE - INTERVAL '1 day' AND pr.base_repo_id = ANY(ARRAY[${repo_id}]::text[])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   },
   "targets": [
    {}
   ]
  }
 ]
}