{
 "title": "DORA Details - Time to Restore Service",
 "tags": [ "DORA" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "SELECT DISTINCT name FROM projects"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard shows the details about [Time to restore service\n](https://devlake.apache.org/docs/Metrics/MTTR) in DORA."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "1. Median Time to Restore Service",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/*  ***** 2021 report ***** -- */ /* Metric 4: Median time to restore service */ WITH _deployments AS (SELECT cdc.cicd_deployment_id AS deployment_id, MAX(cdc.finished_date) AS deployment_finished_date FROM cicd_deployment_commits AS cdc JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE pm.project_name::text IN (SELECT v FROM unnest(CASE WHEN '$project' = '' THEN ARRAY[NULL::text] ELSE ARRAY[$project]::text[] END) v) AND cdc.result = 'SUCCESS' AND cdc.environment = 'PRODUCTION' GROUP BY 1 HAVING MAX(cdc.finished_date) BETWEEN $__timeFrom() AND $__timeTo()), _incidents AS (/* get the incidents created within the selected time period in the top-right corner */ SELECT DISTINCT i.id, CAST(lead_time_minutes AS BIGINT) AS lead_time_minutes FROM incidents AS i JOIN project_mapping AS pm ON i.scope_id = pm.row_id AND pm.\"table\" = i.\"table\" WHERE pm.project_name::text IN (SELECT v FROM unnest(CASE WHEN '${project}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${project}]::text[] END) v) AND $__timeFilter(i.resolution_date)), _median_mttr_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY lead_time_minutes NULLS FIRST) AS ranks FROM _incidents), _median_mttr AS (SELECT MAX(lead_time_minutes) AS median_time_to_resolve FROM _median_mttr_ranks WHERE ranks <= 0.5) SELECT CAST(median_time_to_resolve AS NUMERIC) / NULLIF(60, 0) AS median_time_to_resolve_in_hours FROM _median_mttr"
    }
   ]
  },
  {
   "title": "3. Time to restore service details",
   "type": "table",
   "gridPos": { "h": 19, "w": 19, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "rawSql": "/*  ***** 2021 report ***** -- */ /* Metric 4: Median time to restore service */ WITH _incidents AS (/* get the incidents created within the selected time period in the top-right corner */ SELECT DISTINCT i.id AS \"incident_id\", i.title, i.url, i.url AS \"metric_hidden\", i.resolution_date /* i.created_date, */, CAST(CAST(lead_time_minutes AS NUMERIC) / NULLIF(60, 0) AS BIGINT) AS time_to_restore_service FROM incidents AS i JOIN project_mapping AS pm ON i.scope_id = pm.row_id AND pm.\"table\" = i.\"table\" WHERE pm.project_name::text IN (SELECT v FROM unnest(CASE WHEN '$project' = '' THEN ARRAY[NULL::text] ELSE ARRAY[$project]::text[] END) v) AND $__timeFilter(i.resolution_date)) SELECT * FROM _incidents ORDER BY resolution_date DESC NULLS LAST"
    }
   ]
  },
  {
   "title": "2. Incident Count",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/*  ***** 2021 report ***** -- */ /* Metric 4: Median time to restore service */ WITH _deployments AS (SELECT cdc.cicd_deployment_id AS deployment_id, MAX(cdc.finished_date) AS deployment_finished_date FROM cicd_deployment_commits AS cdc JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE pm.project_name::text IN (SELECT v FROM unnest(CASE WHEN '$project' = '' THEN ARRAY[NULL::text] ELSE ARRAY[$project]::text[] END) v) AND cdc.result = 'SUCCESS' AND cdc.environment = 'PRODUCTION' GROUP BY 1 HAVING MAX(cdc.finished_date) BETWEEN $__timeFrom() AND $__timeTo()), _incidents AS (/* get the incidents created within the selected time period in the top-right corner */ SELECT DISTINCT i.id, CAST(lead_time_minutes AS BIGINT) AS lead_time_minutes FROM incidents AS i JOIN project_mapping AS pm ON i.scope_id = pm.row_id AND pm.\"table\" = i.\"table\" WHERE pm.project_name::text IN (SELECT v FROM unnest(CASE WHEN '${project}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${project}]::text[] END) v) AND $__timeFilter(i.created_date)) SELECT COUNT(id) AS \"incident count\" FROM _incidents"
    }
   ]
  }
 ]
}