{
 "title": "DORA Details - Failed Deployment Recovery Time (PostgreSQL)",
 "tags": [ "DORA" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "select distinct name from projects"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard shows the details about [Failed Deployment Recovery Time\n](https://devlake.apache.org/docs/Metrics/MTTR) in DORA."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "1. Failed Deployment Recovery Time",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/*  ***** 2023 report ***** -- */ /*  Metric 4: Failed deployment recovery time */ WITH _deployments AS (SELECT cdc.cicd_deployment_id AS deployment_id, MAX(cdc.finished_date) AS deployment_finished_date FROM cicd_deployment_commits AS cdc JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE pm.project_name IN ($project) AND cdc.result = 'SUCCESS' AND cdc.environment = 'PRODUCTION' GROUP BY 1 HAVING $__timeFilter(MAX(cdc.finished_date))), _incidents_for_deployments AS (SELECT i.id AS incident_id, i.created_date AS incident_create_date, i.resolution_date AS incident_resolution_date, fd.deployment_id AS caused_by_deployment, fd.deployment_finished_date, TO_CHAR(fd.deployment_finished_date, 'YY/MM') AS deployment_finished_month FROM incidents AS i LEFT JOIN project_incident_deployment_relationships AS pim ON i.id = pim.id JOIN _deployments AS fd ON pim.deployment_id = fd.deployment_id WHERE $__timeFilter(i.resolution_date)), _recovery_time_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY (EXTRACT(EPOCH FROM (incident_resolution_date - deployment_finished_date))/60) NULLS FIRST) AS ranks FROM _incidents_for_deployments), _median_recovery_time AS (SELECT MAX((EXTRACT(EPOCH FROM (incident_resolution_date - deployment_finished_date))/60)) AS median_recovery_time FROM _recovery_time_ranks WHERE ranks <= 0.5), _is_collected_data AS (SELECT CASE WHEN EXISTS(SELECT COUNT(d.deployment_id) FROM _deployments) = 0 AND EXISTS(SELECT COUNT(i.incident_id) FROM incidents) = 0 THEN 'No deployments and incidents' WHEN EXISTS(SELECT COUNT(d.deployment_id) FROM _deployments) = 0 THEN 'No Deployments' WHEN EXISTS(SELECT COUNT(i.incident_id) FROM incidents) = 0 THEN 'No Incidents' ELSE 'No incidents are mapped to deployments' END AS is_collected FROM _deployments AS d, _incidents_for_deployments AS i) SELECT CASE WHEN is_collected = 'No deployments and incidents' THEN 'N/A. Please check if you have collected deployments and incidents.' WHEN is_collected = 'No Deployments' THEN 'N/A. Please check if you have collected deployments.' WHEN is_collected = 'No Incidents' THEN 'N/A. Please check if you have collected incidents.' WHEN NOT median_recovery_time IS NULL THEN CAST(median_recovery_time AS NUMERIC) / NULLIF(60, 0) ELSE 'No data' END AS median_recovery_time_in_hours FROM _median_recovery_time, _is_collected_data"
    }
   ]
  },
  {
   "title": "3. Deployments and Incidents Details",
   "type": "table",
   "gridPos": { "h": 19, "w": 19, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "rawSql": "/*  ***** 2023 report ***** -- */ /*  Metric 4: Failed deployment recovery time */ WITH _deployments AS (SELECT cdc.cicd_deployment_id AS deployment_id, MAX(cdc.finished_date) AS deployment_finished_date FROM cicd_deployment_commits AS cdc JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE pm.project_name IN ($project) AND cdc.result = 'SUCCESS' AND cdc.environment = 'PRODUCTION' GROUP BY 1 HAVING $__timeFilter(MAX(cdc.finished_date))), _incidents_for_deployments AS (SELECT fd.deployment_id AS \"deployment_id\", fd.deployment_finished_date, i.id AS incident_caused_by_deployment /* date_format(fd.deployment_finished_date,'%y/%m') as deployment_finished_month, */, i.title AS incident_title, i.url AS incident_url, i.url AS \"metric_hidden\", i.resolution_date AS incident_resolution_date /* i.created_date as incident_create_date, */, (EXTRACT(EPOCH FROM (i.resolution_date - fd.deployment_finished_date))/3600) AS \"failed_deployment_recovery_time\" FROM incidents AS i LEFT JOIN project_incident_deployment_relationships AS pim ON i.id = pim.id JOIN _deployments AS fd ON pim.deployment_id = fd.deployment_id WHERE $__timeFilter(i.resolution_date)) SELECT * FROM _incidents_for_deployments WHERE NOT incident_resolution_date IS NULL"
    }
   ]
  },
  {
   "title": "2. The number of incidents caused by deployments",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/*  ***** 2023 report ***** -- */ /*  Metric 4: Failed deployment recovery time */ WITH _deployments AS (SELECT cdc.cicd_deployment_id AS deployment_id, MAX(cdc.finished_date) AS deployment_finished_date FROM cicd_deployment_commits AS cdc JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE pm.project_name IN ($project) AND cdc.result = 'SUCCESS' AND cdc.environment = 'PRODUCTION' GROUP BY 1 HAVING $__timeFilter(MAX(cdc.finished_date))), _incidents_for_deployments AS (SELECT i.id AS incident_id, i.created_date AS incident_create_date, i.resolution_date AS incident_resolution_date, fd.deployment_id AS caused_by_deployment, fd.deployment_finished_date, TO_CHAR(fd.deployment_finished_date, 'YY/MM') AS deployment_finished_month FROM incidents AS i LEFT JOIN project_incident_deployment_relationships AS pim ON i.id = pim.id JOIN _deployments AS fd ON pim.deployment_id = fd.deployment_id WHERE $__timeFilter(i.resolution_date)), _incidents /*  ***** 2021 report ***** -- */ /* Metric 4: Median time to restore service */ AS (/* get the incidents created within the selected time period in the top-right corner */ SELECT DISTINCT i.id, CAST(lead_time_minutes AS BIGINT) AS lead_time_minutes FROM incidents AS i JOIN project_mapping AS pm ON i.scope_id = pm.row_id AND i.\"table\" = pm.\"table\" AND pm.\"table\" = 'boards' WHERE pm.project_name = ANY(ARRAY[${project}]::text[]) AND $__timeFilter(i.created_date)) SELECT COUNT(incident_id) AS total_count FROM _incidents_for_deployments"
    }
   ]
  }
 ]
}