{
 "title": "Engineering Throughput and Cycle Time",
 "tags": [
  "Engineering Leads Dashboard",
  "Highlights"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "SELECT DISTINCT name FROM projects"
   },
   {
    "name": "priority",
    "label": "P0+P1 Priority",
    "query": "SELECT DISTINCT priority FROM issues WHERE priority <> ''"
   },
   {
    "name": "interval",
    "label": "Time Interval",
    "query": "Month : DAYOFMONTH, Week : WEEKDAY"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard shows the engineering throughput and and cycle time, which helps to identify productivity and bottlenecks of the development process.\n- Data Sources Required:\n   - One of the Git tools, e.g. [GitHub](https://devlake.apache.org/docs/Configuration/GitHub), [GitLab](https://devlake.apache.org/docs/Configuration/GitLab), [Bitbucket](https://devlake.apache.org/docs/Configuration/BitBucket) or [Azure DevOps](https://devlake.apache.org/docs/Configuration/AzureDevOps)\n   - One of the issue tracking tools, e.g. [Jira](https://devlake.apache.org/docs/Configuration/Jira) ([Scope Config](https://devlake.apache.org/docs/UserManuals/ConfigUI/Jira#step-3---adding-transformation-rules-optional) required to tell DevLake what the story_points field is)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "1. Throughput/Quality",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PRs Opened/Merged",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT CAST(pr.created_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(pr.created_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(pr.created_date AS DATE)) - 1) END + 1) AS time, COUNT(DISTINCT pr.id) AS \"PR: Opened\", COUNT(DISTINCT CASE WHEN NOT pr.merged_date IS NULL THEN id ELSE NULL END) AS \"PR: Merged\" FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' WHERE $__timeFilter(pr.created_date) AND pm.project_name::text IN (SELECT v FROM unnest(CASE WHEN '${project}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${project}]::text[] END) v) GROUP BY 1"
    }
   ]
  },
  {
   "title": "Issue Opened/Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT CAST(i.created_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(i.created_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(i.created_date AS DATE)) - 1) END + 1) AS time, COUNT(DISTINCT i.id) AS \"Issues Opened\", COUNT(DISTINCT CASE WHEN i.status = 'DONE' THEN i.id ELSE NULL END) AS \"Issues Completed\" FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id WHERE $__timeFilter(i.created_date) AND pm.project_name::text IN (SELECT v FROM unnest(CASE WHEN '${project}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${project}]::text[] END) v) GROUP BY 1"
    }
   ]
  },
  {
   "title": "Issue Story Points Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT CAST(i.resolution_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(i.resolution_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(i.resolution_date AS DATE)) - 1) END + 1) AS time, SUM(CASE WHEN i.status = 'DONE' THEN i.story_point ELSE 0 END) AS \"Story Points Completed\" FROM (SELECT DISTINCT i.id, i.resolution_date, i.status, i.story_point FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id WHERE $__timeFilter(i.resolution_date) AND pm.project_name::text IN (SELECT v FROM unnest(CASE WHEN '${project}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${project}]::text[] END) v)) AS i GROUP BY 1 ORDER BY 1 NULLS FIRST"
    }
   ]
  },
  {
   "title": "PR Review Depth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT CAST(pr.created_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(pr.created_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(pr.created_date AS DATE)) - 1) END + 1) AS time, CAST(COUNT(DISTINCT prc.id) AS NUMERIC) / NULLIF(COUNT(DISTINCT pr.id), 0) AS \"PR Review Depth\" FROM pull_requests AS pr LEFT JOIN pull_request_comments AS prc ON pr.id = prc.pull_request_id JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' WHERE $__timeFilter(pr.created_date) AND pm.project_name::text IN (SELECT v FROM unnest(CASE WHEN '${project}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${project}]::text[] END) v) AND NOT pr.merged_date IS NULL GROUP BY 1"
    }
   ]
  },
  {
   "title": "P0/P1 Bugs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT CAST(i.created_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(i.created_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(i.created_date AS DATE)) - 1) END + 1) AS time, COUNT(DISTINCT i.id) AS \"P0/P1 Bugs\" FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id WHERE $__timeFilter(i.created_date) AND pm.project_name::text IN (SELECT v FROM unnest(CASE WHEN '${project}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${project}]::text[] END) v) AND i.type = 'BUG' AND i.priority::text IN (SELECT v FROM unnest(CASE WHEN '${priority}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${priority}]::text[] END) v) GROUP BY 1"
    }
   ]
  },
  {
   "title": "PR Merged Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "rawSql": "WITH _pr_commits_data AS (SELECT CAST(pr.created_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(pr.created_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(pr.created_date AS DATE)) - 1) END + 1) AS time, pr.id AS pr_id, pr.merge_commit_sha, SUM(c.additions) + SUM(c.deletions) AS loc FROM pull_requests AS pr LEFT JOIN commits AS c ON pr.merge_commit_sha = c.sha JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' WHERE $__timeFilter(pr.created_date) AND pm.project_name::text IN (SELECT v FROM unnest(CASE WHEN '${project}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${project}]::text[] END) v) AND pr.status = 'MERGED' GROUP BY 1, 2, 3) SELECT time, CAST(SUM(loc) AS NUMERIC) / NULLIF(COUNT(DISTINCT pr_id), 0) AS \"PR Merged Size\" FROM _pr_commits_data GROUP BY 1"
    }
   ]
  },
  {
   "title": "PRs Merged w/o Review",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT CAST(pr.created_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(pr.created_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(pr.created_date AS DATE)) - 1) END + 1) AS time, SUM(CASE WHEN NOT pr.id IN (SELECT pull_request_id FROM pull_request_comments) THEN 1 ELSE 0 END) AS \"PRs Merged w/o Review\" FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' WHERE $__timeFilter(pr.created_date) AND pm.project_name::text IN (SELECT v FROM unnest(CASE WHEN '${project}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${project}]::text[] END) v) AND NOT pr.merged_date IS NULL GROUP BY 1 ORDER BY 1 NULLS FIRST"
    }
   ]
  },
  {
   "title": "2. Cycle Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PR Cycle Time [Merged PRs]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "WITH _prs AS (SELECT pr.id, pr.merged_date AS pr_merged_date, COALESCE(CAST(prm.pr_cycle_time AS NUMERIC) / NULLIF(60, 0), 0) AS cycle_time /* convert null to 0 if a PR has no cycle_time to make sure cycle_time equals the sum of the four metrics below */ FROM pull_requests AS pr LEFT JOIN project_pr_metrics AS prm ON pr.id = prm.id JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' WHERE $__timeFilter(pr.merged_date) AND pr.created_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH' AND pm.project_name::text IN (SELECT v FROM unnest(CASE WHEN '${project}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${project}]::text[] END) v) GROUP BY 1, 2, 3) SELECT CAST(pr_merged_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(pr_merged_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(pr_merged_date AS DATE)) - 1) END + 1) AS time, AVG(cycle_time) AS \"PR Cycle Time(h)\" FROM _prs GROUP BY 1 ORDER BY 1 NULLS FIRST"
    }
   ]
  },
  {
   "title": "PR Coding Time [Merged PRs]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "WITH _prs AS (SELECT pr.id, pr.merged_date AS pr_merged_date, COALESCE(CAST(prm.pr_coding_time AS NUMERIC) / NULLIF(60, 0), 0) AS coding_time /* convert null to 0 if a PR has no coding_time to make sure cycle_time equals the sum of the four sub-metrics */ FROM pull_requests AS pr LEFT JOIN project_pr_metrics AS prm ON pr.id = prm.id JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' WHERE $__timeFilter(pr.merged_date) AND pr.merged_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH' AND pm.project_name::text IN (SELECT v FROM unnest(CASE WHEN '${project}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${project}]::text[] END) v) GROUP BY 1, 2, 3) SELECT CAST(pr_merged_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(pr_merged_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(pr_merged_date AS DATE)) - 1) END + 1) AS time, AVG(coding_time) AS \"Coding Time(h)\" FROM _prs GROUP BY 1 ORDER BY 1 NULLS FIRST"
    }
   ]
  },
  {
   "title": "PR Pickup Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "targets": [
    {
     "rawSql": "WITH _prs AS (SELECT pr.id, pr.merged_date AS pr_merged_date, COALESCE(CAST(prm.pr_pickup_time AS NUMERIC) / NULLIF(60, 0), 0) AS pickup_time /* convert null to 0 if a PR has no pickup_time to make sure cycle_time equals the sum of the four sub-metrics */ FROM pull_requests AS pr LEFT JOIN project_pr_metrics AS prm ON pr.id = prm.id JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' WHERE $__timeFilter(pr.merged_date) AND pr.merged_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH' AND pm.project_name::text IN (SELECT v FROM unnest(CASE WHEN '${project}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${project}]::text[] END) v) GROUP BY 1, 2, 3) SELECT CAST(pr_merged_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(pr_merged_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(pr_merged_date AS DATE)) - 1) END + 1) AS time, AVG(pickup_time) AS \"Pickup Time(h)\" FROM _prs GROUP BY 1 ORDER BY 1 NULLS FIRST"
    }
   ]
  },
  {
   "title": "PR Review Time [Merged PRs]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "targets": [
    {
     "rawSql": "WITH _prs AS (SELECT pr.id, pr.merged_date AS pr_merged_date, COALESCE(CAST(prm.pr_review_time AS NUMERIC) / NULLIF(60, 0), 0) AS review_time /* convert null to 0 if a PR has no review_time to make sure cycle_time equals the sum of the four sub-metrics */ FROM pull_requests AS pr LEFT JOIN project_pr_metrics AS prm ON pr.id = prm.id JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' WHERE $__timeFilter(pr.created_date) AND pr.merged_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH' AND pm.project_name::text IN (SELECT v FROM unnest(CASE WHEN '${project}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${project}]::text[] END) v) GROUP BY 1, 2, 3) SELECT CAST(pr_merged_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(pr_merged_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(pr_merged_date AS DATE)) - 1) END + 1) AS time, AVG(review_time) AS \"Review Time(h)\" FROM _prs GROUP BY 1 ORDER BY 1 NULLS FIRST"
    }
   ]
  },
  {
   "title": "PR Deploy Time [Merged PRs]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "targets": [
    {
     "rawSql": "WITH _prs AS (SELECT pr.id, pr.merged_date AS pr_merged_date, COALESCE(CAST(prm.pr_deploy_time AS NUMERIC) / NULLIF(60, 0), 0) AS deploy_time /* convert null to 0 if a PR has no deploy_time to make sure cycle_time equals the sum of the four sub-metrics */ FROM pull_requests AS pr LEFT JOIN project_pr_metrics AS prm ON pr.id = prm.id JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' WHERE $__timeFilter(pr.merged_date) AND pr.merged_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH' AND pm.project_name::text IN (SELECT v FROM unnest(CASE WHEN '${project}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${project}]::text[] END) v) GROUP BY 1, 2, 3) SELECT CAST(pr_merged_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(pr_merged_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(pr_merged_date AS DATE)) - 1) END + 1) AS time, AVG(deploy_time) AS \"PR Deploy Time(h)\" FROM _prs GROUP BY 1 ORDER BY 1 NULLS FIRST"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 40 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   },
   "targets": [
    {}
   ]
  }
 ]
}