{
 "title": "GitHub_Release_Quality_and_Contribution_Analysis (PostgreSQL)",
 "tags": [ "OSS Maintainer Dashboard" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repo_id",
    "label": "Repo",
    "query": "select concat(name, '--', id) as text from repos"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard can be used to track bugs.\n- Data Source Required: GitHub ([transformation](https://devlake.apache.org/docs/UserManuals/ConfigUI/GitHub#step-3---adding-transformation-rules-optional) required. Additional settings are required to get version data)."
   },
   "targets": [
    {}
   ]
  },
  { "title": "Quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "1. Bug Distribution [Minor Versions]",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* Get the bug distribution in major versions */ WITH bugs_in_each_tag AS (SELECT SUBSTRING_INDEX(rid.new_ref_id, 'refs/tags/', -1) AS tag_name, SUBSTRING_INDEX(rid.new_ref_id, ':', 4) AS repo_id, i.issue_key, i.type, i.title, i.description FROM refs_issues_diffs AS rid LEFT JOIN issues AS i ON rid.issue_id = i.id WHERE SUBSTRING_INDEX(rid.new_ref_id, ':', 4) IN (${repo_id}) AND i.type = 'BUG') SELECT CONCAT(SUBSTRING_INDEX(biet.tag_name, '.', 3), '.x') AS minor_version, COUNT(*) AS bug_count FROM bugs_in_each_tag AS biet GROUP BY 1"
    }
   ]
  },
  {
   "title": "2.1 Ratio of Bug Fix Commits [Last 5 Tags]",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "/* Get the number of fixed bugs in the last 5 tags */ WITH refs_commits_diffs AS (SELECT new_refs.id AS new_ref_id, old_refs.id AS old_ref_id, commits_diffs.commit_sha, new_commit_sha, old_commit_sha FROM commits_diffs LEFT JOIN refs AS new_refs ON new_refs.commit_sha = commits_diffs.new_commit_sha LEFT JOIN refs AS old_refs ON old_refs.commit_sha = commits_diffs.old_commit_sha), _last_5_tags AS (SELECT DISTINCT SUBSTRING_INDEX(new_ref_id, ':', -1) AS new_ref_id, SUBSTRING_INDEX(old_ref_id, ':', -1) AS old_ref_id /* distinct new_ref_id, old_ref_id */ FROM refs_commits_diffs WHERE SUBSTRING_INDEX(new_ref_id, ':', 4) IN (${repo_id}) ORDER BY 1 DESC NULLS LAST LIMIT 5), _bugs_of_tags AS (SELECT SUBSTRING_INDEX(rid.new_ref_id, 'tags/', -1) AS tag_name, COUNT(*) AS bug_count /* SUBSTRING_INDEX(rid.new_ref_id,':', 3) as repo_id, */ FROM refs_issues_diffs AS rid LEFT JOIN issues AS i ON rid.issue_id = i.id WHERE SUBSTRING_INDEX(rid.new_ref_id, ':', 4) IN (${repo_id}) AND /* and rid.new_ref_id in (SELECT new_ref_id FROM _last_5_tags) */ SUBSTRING_INDEX(rid.new_ref_id, ':', -1) IN (SELECT new_ref_id FROM _last_5_tags) AND i.type = 'BUG' GROUP BY 1), _combine_pr AS (SELECT pull_request_id AS id, commit_sha FROM pull_request_commits LEFT JOIN pull_requests AS p ON pull_request_commits.pull_request_id = p.id WHERE p.base_repo_id = ANY(ARRAY[${repo_id}]::text[]) UNION SELECT id, merge_commit_sha AS commit_sha FROM pull_requests WHERE base_repo_id = ANY(ARRAY[${repo_id}]::text[])), _commit_count_of_pr AS (SELECT SUBSTRING_INDEX(rcd.new_ref_id, 'tags/', -1) AS tag_name, SUBSTRING_INDEX(rcd.new_ref_id, ':', 4) AS repo_id, pr.id AS pull_request_id, COUNT(c.sha) AS commit_count FROM refs_commits_diffs AS rcd LEFT JOIN commits AS c ON rcd.commit_sha = c.sha /* left join pull_request_commits prc on c.sha = prc.commit_sha */ LEFT JOIN _combine_pr AS pr ON c.sha = pr.commit_sha WHERE SUBSTRING_INDEX(rcd.new_ref_id, ':', 4) IN (${repo_id}) AND /* and rcd.new_ref_id in (SELECT new_ref_id FROM _last_5_tags) */ SUBSTRING_INDEX(rcd.new_ref_id, ':', -1) IN (SELECT SUBSTRING_INDEX(new_ref_id, ':', -1) FROM _last_5_tags) GROUP BY 1, 2, 3), _pr_worktype AS (SELECT DISTINCT pri.pull_request_id, i.type FROM pull_request_issues AS pri LEFT JOIN pull_requests AS pr ON pri.pull_request_id = pr.id LEFT JOIN issues AS i ON pri.issue_id = i.id WHERE i.issue_key <> 0), _pr_elco_and_worktype AS (SELECT ccop.tag_name, CAST(SUM(CASE WHEN pw.type = 'BUG' THEN commit_count ELSE 0 END) AS NUMERIC) / NULLIF(SUM(commit_count), 0) AS cost_percentage FROM _commit_count_of_pr AS ccop LEFT JOIN _pr_worktype AS pw ON ccop.pull_request_id = pw.pull_request_id GROUP BY 1) SELECT bot.tag_name, bot.bug_count, peaw.cost_percentage AS \"cost_percentage(bugfixing commits/total commits)\" FROM _bugs_of_tags AS bot JOIN _pr_elco_and_worktype AS peaw ON bot.tag_name = peaw.tag_name ORDER BY 1 NULLS FIRST"
    }
   ]
  },
  {
   "title": "2.2 Severity Distribution [Last Tag]",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* Get the  severity distribution in bugs */ /* Get the work-type distribution in the last n tags */ WITH refs_commits_diffs AS (SELECT new_refs.id AS new_ref_id, old_refs.id AS old_ref_id, commits_diffs.commit_sha, new_commit_sha, old_commit_sha FROM commits_diffs LEFT JOIN refs AS new_refs ON new_refs.commit_sha = commits_diffs.new_commit_sha LEFT JOIN refs AS old_refs ON old_refs.commit_sha = commits_diffs.old_commit_sha), _last_n_tags AS (SELECT DISTINCT /* distinct new_ref_id, old_ref_id */ SUBSTRING_INDEX(new_ref_id, ':', -1) AS new_ref_id, SUBSTRING_INDEX(old_ref_id, ':', -1) AS old_ref_id FROM refs_commits_diffs WHERE SUBSTRING_INDEX(new_ref_id, ':', 4) IN (${repo_id}) ORDER BY 1 DESC NULLS LAST LIMIT 1), bugs_in_each_tag AS (SELECT SUBSTRING_INDEX(rid.new_ref_id, 'refs/tags/', -1) AS tag_name, SUBSTRING_INDEX(rid.new_ref_id, ':', 4) AS repo_id, i.issue_key, i.type, i.title, i.description, i.severity FROM refs_issues_diffs AS rid LEFT JOIN issues AS i ON rid.issue_id = i.id WHERE SUBSTRING_INDEX(rid.new_ref_id, ':', 4) IN (${repo_id}) AND /* and rid.new_ref_id in (SELECT new_ref_id FROM _last_n_tags) */ SUBSTRING_INDEX(rid.new_ref_id, ':', -1) IN (SELECT new_ref_id FROM _last_n_tags) AND i.type = 'BUG') SELECT CONCAT(biet.tag_name, \" \", CASE WHEN biet.severity <> '' THEN biet.severity ELSE 'UNKNOWN' END) AS severity, COUNT(*) AS bug_count FROM bugs_in_each_tag AS biet GROUP BY 1"
    }
   ]
  },
  {
   "title": "2.3 Severity Distribution [The Tag before Last]",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* Get the  severity distribution in bugs */ /* Get the work-type distribution in the last n tags */ WITH refs_commits_diffs AS (SELECT new_refs.id AS new_ref_id, old_refs.id AS old_ref_id, commits_diffs.commit_sha, new_commit_sha, old_commit_sha FROM commits_diffs LEFT JOIN refs AS new_refs ON new_refs.commit_sha = commits_diffs.new_commit_sha LEFT JOIN refs AS old_refs ON old_refs.commit_sha = commits_diffs.old_commit_sha), _last_n_tags AS (SELECT DISTINCT /* distinct new_ref_id, old_ref_id */ SUBSTRING_INDEX(new_ref_id, ':', -1) AS new_ref_id, SUBSTRING_INDEX(old_ref_id, ':', -1) AS old_ref_id FROM refs_commits_diffs WHERE SUBSTRING_INDEX(new_ref_id, ':', 4) IN (${repo_id}) ORDER BY 1 DESC NULLS LAST LIMIT 1 OFFSET 1), bugs_in_each_tag AS (SELECT SUBSTRING_INDEX(rid.new_ref_id, 'refs/tags/', -1) AS tag_name, SUBSTRING_INDEX(rid.new_ref_id, ':', 4) AS repo_id, i.issue_key, i.type, i.title, i.description, i.severity FROM refs_issues_diffs AS rid LEFT JOIN issues AS i ON rid.issue_id = i.id WHERE SUBSTRING_INDEX(rid.new_ref_id, ':', 4) IN (${repo_id}) AND /* and rid.new_ref_id in (SELECT new_ref_id FROM _last_n_tags) */ SUBSTRING_INDEX(rid.new_ref_id, ':', -1) IN (SELECT new_ref_id FROM _last_n_tags) AND i.type = 'BUG') SELECT CONCAT(biet.tag_name, \" \", CASE WHEN biet.severity <> '' THEN biet.severity ELSE 'UNKNOWN' END) AS severity, COUNT(*) AS bug_count FROM bugs_in_each_tag AS biet GROUP BY 1"
    }
   ]
  },
  {
   "title": "2.4 Severity Distribution [The 2nd Tag before Last]",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* Get the  severity distribution in bugs */ /* Get the work-type distribution in the last n tags */ WITH refs_commits_diffs AS (SELECT new_refs.id AS new_ref_id, old_refs.id AS old_ref_id, commits_diffs.commit_sha, new_commit_sha, old_commit_sha FROM commits_diffs LEFT JOIN refs AS new_refs ON new_refs.commit_sha = commits_diffs.new_commit_sha LEFT JOIN refs AS old_refs ON old_refs.commit_sha = commits_diffs.old_commit_sha), _last_n_tags AS (SELECT DISTINCT /* distinct new_ref_id, old_ref_id */ SUBSTRING_INDEX(new_ref_id, ':', -1) AS new_ref_id, SUBSTRING_INDEX(old_ref_id, ':', -1) AS old_ref_id FROM refs_commits_diffs WHERE SUBSTRING_INDEX(new_ref_id, ':', 4) IN (${repo_id}) ORDER BY 1 DESC NULLS LAST LIMIT 1 OFFSET 2), bugs_in_each_tag AS (SELECT SUBSTRING_INDEX(rid.new_ref_id, 'refs/tags/', -1) AS tag_name, SUBSTRING_INDEX(rid.new_ref_id, ':', 4) AS repo_id, i.issue_key, i.type, i.title, i.description, i.severity FROM refs_issues_diffs AS rid LEFT JOIN issues AS i ON rid.issue_id = i.id WHERE SUBSTRING_INDEX(rid.new_ref_id, ':', 4) IN (${repo_id}) AND /* and rid.new_ref_id in (SELECT new_ref_id FROM _last_n_tags) */ SUBSTRING_INDEX(rid.new_ref_id, ':', -1) IN (SELECT new_ref_id FROM _last_n_tags) AND i.type = 'BUG') SELECT CONCAT(biet.tag_name, \" \", CASE WHEN biet.severity <> '' THEN biet.severity ELSE 'UNKNOWN' END) AS severity, COUNT(*) AS bug_count FROM bugs_in_each_tag AS biet GROUP BY 1"
    }
   ]
  },
  {
   "title": "2.5 List of Fixed Bugs [Last 5 Tags]",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "/* Get the number of fixed bugs in the last 5 tags */ WITH refs_commits_diffs AS (SELECT new_refs.id AS new_ref_id, old_refs.id AS old_ref_id, commits_diffs.commit_sha, new_commit_sha, old_commit_sha FROM commits_diffs LEFT JOIN refs AS new_refs ON new_refs.commit_sha = commits_diffs.new_commit_sha LEFT JOIN refs AS old_refs ON old_refs.commit_sha = commits_diffs.old_commit_sha), _last_5_tags AS (SELECT DISTINCT /* distinct new_ref_id, old_ref_id */ SUBSTRING_INDEX(new_ref_id, ':', -1) AS new_ref_id, SUBSTRING_INDEX(old_ref_id, ':', -1) AS old_ref_id FROM refs_commits_diffs WHERE SUBSTRING_INDEX(new_ref_id, ':', 4) IN (${repo_id}) ORDER BY 1 DESC NULLS LAST LIMIT 5) SELECT DISTINCT b.name AS repo_name, SUBSTRING_INDEX(rid.new_ref_id, 'tags/', -1) AS tag_name, i.issue_key AS issue_key, i.title, i.assignee_name, CAST(i.lead_time_minutes AS NUMERIC) / NULLIF(1440, 0) AS lead_time_in_days, CONCAT(b.url, '/', i.issue_key) AS url FROM refs_issues_diffs AS rid LEFT JOIN issues AS i ON rid.issue_id = i.id JOIN boards AS b ON SUBSTRING_INDEX(rid.new_ref_id, ':', 4) = b.id WHERE SUBSTRING_INDEX(rid.new_ref_id, ':', 4) IN (${repo_id}) AND /* and rid.new_ref_id in (SELECT new_ref_id FROM _last_5_tags) */ SUBSTRING_INDEX(rid.new_ref_id, ':', -1) IN (SELECT SUBSTRING_INDEX(new_ref_id, ':', -1) FROM _last_5_tags) AND i.type = 'BUG' ORDER BY tag_name DESC NULLS LAST"
    }
   ]
  },
  {
   "title": "3.1 Ratio of Issues with 'Component' Label [Last 5 Tags]",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* Component distribution of bugs fixed in the last 5 tags */ WITH refs_commits_diffs AS (SELECT new_refs.id AS new_ref_id, old_refs.id AS old_ref_id, commits_diffs.commit_sha, new_commit_sha, old_commit_sha FROM commits_diffs LEFT JOIN refs AS new_refs ON new_refs.commit_sha = commits_diffs.new_commit_sha LEFT JOIN refs AS old_refs ON old_refs.commit_sha = commits_diffs.old_commit_sha), _last_5_tags AS (SELECT DISTINCT /* distinct new_ref_id, old_ref_id */ SUBSTRING_INDEX(new_ref_id, ':', -1) AS new_ref_id, SUBSTRING_INDEX(old_ref_id, ':', -1) AS old_ref_id FROM refs_commits_diffs WHERE SUBSTRING_INDEX(new_ref_id, ':', 4) IN (${repo_id}) ORDER BY 1 DESC NULLS LAST LIMIT 5), bugs_in_each_tag AS (SELECT SUBSTRING_INDEX(rid.new_ref_id, 'refs/', -1) AS tag_name, SUBSTRING_INDEX(rid.new_ref_id, ':', 4) AS repo_id, i.issue_key, i.component, i.severity, i.title, i.description FROM refs_issues_diffs AS rid LEFT JOIN issues AS i ON rid.issue_id = i.id WHERE SUBSTRING_INDEX(rid.new_ref_id, ':', 4) IN (${repo_id}) AND /* and rid.new_ref_id in (SELECT new_ref_id FROM _last_5_tags) */ SUBSTRING_INDEX(rid.new_ref_id, ':', -1) IN (SELECT new_ref_id FROM _last_5_tags) AND i.type = 'BUG') SELECT CASE WHEN component = '' THEN 'unlabeled' ELSE 'labeled' END AS component, COUNT(*) AS bug_count FROM bugs_in_each_tag AS biet GROUP BY 1"
    }
   ]
  },
  {
   "title": "3.2 Source of Bugs by Component [Last 5 Tags]",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* Component distribution of bugs fixed in the last 5 tags */ WITH refs_commits_diffs AS (SELECT new_refs.id AS new_ref_id, old_refs.id AS old_ref_id, commits_diffs.commit_sha, new_commit_sha, old_commit_sha FROM commits_diffs LEFT JOIN refs AS new_refs ON new_refs.commit_sha = commits_diffs.new_commit_sha LEFT JOIN refs AS old_refs ON old_refs.commit_sha = commits_diffs.old_commit_sha), _last_5_tags AS (SELECT DISTINCT /* distinct new_ref_id, old_ref_id */ SUBSTRING_INDEX(new_ref_id, ':', -1) AS new_ref_id, SUBSTRING_INDEX(old_ref_id, ':', -1) AS old_ref_id FROM refs_commits_diffs WHERE SUBSTRING_INDEX(new_ref_id, ':', 4) IN (${repo_id}) ORDER BY 1 DESC NULLS LAST LIMIT 5), bugs_in_each_tag AS (SELECT SUBSTRING_INDEX(rid.new_ref_id, 'refs/', -1) AS tag_name, SUBSTRING_INDEX(rid.new_ref_id, ':', 4) AS repo_id, i.issue_key, i.component, i.severity, i.title, i.description FROM refs_issues_diffs AS rid LEFT JOIN issues AS i ON rid.issue_id = i.id WHERE SUBSTRING_INDEX(rid.new_ref_id, ':', 4) IN (${repo_id}) AND /* and rid.new_ref_id in (SELECT new_ref_id FROM _last_5_tags) */ SUBSTRING_INDEX(rid.new_ref_id, ':', -1) IN (SELECT new_ref_id FROM _last_5_tags) AND i.type = 'BUG') SELECT component, COUNT(*) AS bug_count FROM bugs_in_each_tag AS biet WHERE component <> '' GROUP BY 1"
    }
   ]
  },
  {
   "title": "4.1 Contributor Fixing 80%+ Bugs [Last 5 Tags]",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* Get the % of contributors who fixed 80% of bugs in the last 5 tags */ WITH refs_commits_diffs AS (SELECT new_refs.id AS new_ref_id, old_refs.id AS old_ref_id, commits_diffs.commit_sha, new_commit_sha, old_commit_sha FROM commits_diffs LEFT JOIN refs AS new_refs ON new_refs.commit_sha = commits_diffs.new_commit_sha LEFT JOIN refs AS old_refs ON old_refs.commit_sha = commits_diffs.old_commit_sha), _last_5_tags AS (SELECT DISTINCT /* distinct new_ref_id, old_ref_id */ SUBSTRING_INDEX(new_ref_id, ':', -1) AS new_ref_id, SUBSTRING_INDEX(old_ref_id, ':', -1) AS old_ref_id FROM refs_commits_diffs WHERE SUBSTRING_INDEX(new_ref_id, ':', 4) IN (${repo_id}) ORDER BY 1 DESC NULLS LAST LIMIT 5), _bugs AS (SELECT i.issue_key, i.type, i.severity, i.title, i.description, pr.id, pr.author_name AS pr_author, pr.created_date, RANK() OVER (PARTITION BY i.id ORDER BY pr.created_date ASC NULLS FIRST) AS pr_rank FROM refs_issues_diffs AS rid LEFT JOIN issues AS i ON rid.issue_id = i.id LEFT JOIN pull_request_issues AS pri ON i.id = pri.issue_id LEFT JOIN pull_requests AS pr ON pri.pull_request_id = pr.id WHERE SUBSTRING_INDEX(rid.new_ref_id, ':', 4) IN (${repo_id}) AND /* and rid.new_ref_id in (SELECT new_ref_id FROM _last_5_tags) */ SUBSTRING_INDEX(rid.new_ref_id, ':', -1) IN (SELECT new_ref_id FROM _last_5_tags) AND i.type = 'BUG' ORDER BY i.issue_key NULLS FIRST), _bug_fixed_count AS (SELECT pr_author, COUNT(*) AS bug_fixed_count FROM _bugs WHERE pr_rank = 1 GROUP BY 1), _bug_fixed_count_running_total AS (SELECT *, SUM(bug_fixed_count) OVER (ORDER BY bug_fixed_count DESC NULLS LAST) AS running_total FROM _bug_fixed_count), _percentile AS (SELECT pr_author, bug_fixed_count, CAST(running_total AS NUMERIC) / NULLIF(SUM(bug_fixed_count) OVER (), 0) AS cumulative_percentage FROM _bug_fixed_count_running_total) SELECT CAST(COUNT(CASE WHEN cumulative_percentage <= 0.8 THEN pr_author ELSE NULL END) AS NUMERIC) / NULLIF(COUNT(*), 0) AS \"% of contributors who fixed 80% of the bugs\" FROM _percentile"
    }
   ]
  },
  {
   "title": "4.2 Top Bug Fixers [Last 5 Tags]",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "/* Get the bug fixer distribution in the last 5 tags */ WITH refs_commits_diffs AS (SELECT new_refs.id AS new_ref_id, old_refs.id AS old_ref_id, commits_diffs.commit_sha, new_commit_sha, old_commit_sha FROM commits_diffs LEFT JOIN refs AS new_refs ON new_refs.commit_sha = commits_diffs.new_commit_sha LEFT JOIN refs AS old_refs ON old_refs.commit_sha = commits_diffs.old_commit_sha), _last_5_tags AS (SELECT DISTINCT /* distinct new_ref_id, old_ref_id */ SUBSTRING_INDEX(new_ref_id, ':', -1) AS new_ref_id, SUBSTRING_INDEX(old_ref_id, ':', -1) AS old_ref_id FROM refs_commits_diffs WHERE SUBSTRING_INDEX(new_ref_id, ':', 4) IN (${repo_id}) ORDER BY 1 DESC NULLS LAST LIMIT 5), _bugs AS (SELECT i.issue_key, i.type, i.severity, i.title, i.description, pr.id, pr.author_name AS pr_author, pr.created_date, RANK() OVER (PARTITION BY i.id ORDER BY pr.created_date ASC NULLS FIRST) AS pr_rank FROM refs_issues_diffs AS rid LEFT JOIN issues AS i ON rid.issue_id = i.id LEFT JOIN pull_request_issues AS pri ON i.id = pri.issue_id LEFT JOIN pull_requests AS pr ON pri.pull_request_id = pr.id WHERE SUBSTRING_INDEX(rid.new_ref_id, ':', 4) IN (${repo_id}) AND /* and rid.new_ref_id in (SELECT new_ref_id FROM _last_5_tags) */ SUBSTRING_INDEX(rid.new_ref_id, ':', -1) IN (SELECT new_ref_id FROM _last_5_tags) AND i.type = 'BUG' ORDER BY i.issue_key NULLS FIRST) SELECT pr_author, COUNT(*) AS bug_fixed_count FROM _bugs WHERE pr_rank = 1 GROUP BY 1 ORDER BY 2 DESC NULLS LAST LIMIT 10"
    }
   ]
  },
  {
   "title": "5.1 Mean Bug Age in Days [All History]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* Get the avg bug age in history */ SELECT CAST(AVG(lead_time_minutes) AS NUMERIC) / NULLIF(1440, 0) AS average_bug_age FROM issues LEFT JOIN board_issues AS bi ON issues.id = bi.issue_id WHERE type = 'BUG' AND status = 'DONE' AND bi.board_id = ANY(ARRAY[${repo_id}]::text[])"
    }
   ]
  },
  {
   "title": "5.2 Mean + Median Bug Age Days [Last 5 Tags]",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "/* Get the bug age in the last 5 tags */ WITH refs_commits_diffs AS (SELECT new_refs.id AS new_ref_id, old_refs.id AS old_ref_id, commits_diffs.commit_sha, new_commit_sha, old_commit_sha FROM commits_diffs LEFT JOIN refs AS new_refs ON new_refs.commit_sha = commits_diffs.new_commit_sha LEFT JOIN refs AS old_refs ON old_refs.commit_sha = commits_diffs.old_commit_sha), _last_5_tags AS (SELECT DISTINCT SUBSTRING_INDEX(new_ref_id, ':', -1) AS new_ref_id, SUBSTRING_INDEX(old_ref_id, ':', -1) AS old_ref_id FROM refs_commits_diffs WHERE SUBSTRING_INDEX(new_ref_id, ':', 4) IN (${repo_id}) ORDER BY 1 DESC NULLS LAST LIMIT 5), _bugs AS (SELECT DISTINCT SUBSTRING_INDEX(rid.new_ref_id, 'tags/', -1) AS tag_name, i.id, i.lead_time_minutes FROM refs_issues_diffs AS rid LEFT JOIN issues AS i ON rid.issue_id = i.id LEFT JOIN pull_request_issues AS pri ON i.id = pri.issue_id WHERE SUBSTRING_INDEX(rid.new_ref_id, ':', 4) IN (${repo_id}) AND /* and rid.new_ref_id in (SELECT new_ref_id FROM _last_5_tags) */ SUBSTRING_INDEX(rid.new_ref_id, ':', -1) IN (SELECT new_ref_id FROM _last_5_tags) AND i.type = 'BUG'), _bugs_percentile AS (SELECT *, PERCENT_RANK() OVER (PARTITION BY tag_name ORDER BY lead_time_minutes NULLS FIRST) AS percentile FROM _bugs ORDER BY 1 NULLS FIRST), _avg_bug_age AS (SELECT tag_name, CAST(AVG(lead_time_minutes) AS NUMERIC) / NULLIF(1440, 0) AS average_bug_age FROM _bugs_percentile GROUP BY 1), _50th_bug_age AS (SELECT tag_name, CAST(MIN(lead_time_minutes) AS NUMERIC) / NULLIF(1440, 0) AS \"50th_bug_age\" FROM _bugs_percentile WHERE percentile >= 0.5 GROUP BY 1) SELECT aba.*, eba.\"50th_bug_age\" FROM _avg_bug_age AS aba JOIN _50th_bug_age AS eba ON aba.tag_name = eba.tag_name"
    }
   ]
  },
  {
   "title": "5.3 Median Bug Age in Days [All History]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* Get the 80th perccentile bug age in history */ WITH _bugs_percentile AS (SELECT id, lead_time_minutes, PERCENT_RANK() OVER (ORDER BY lead_time_minutes NULLS FIRST) AS percentile FROM issues WHERE type = 'BUG' AND status = 'DONE') SELECT CAST(MIN(lead_time_minutes) AS NUMERIC) / NULLIF(1440, 0) AS \"80th_bug_age\" FROM _bugs_percentile WHERE percentile >= 0.5"
    }
   ]
  },
  {
   "title": "5.4 List of Long-Lead Bugs [Closed Bugs in Last 5  Tags]",
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "/* Get the bug fixer distribution in the last 5 tags */ WITH refs_commits_diffs AS (SELECT new_refs.id AS new_ref_id, old_refs.id AS old_ref_id, commits_diffs.commit_sha, new_commit_sha, old_commit_sha FROM commits_diffs LEFT JOIN refs AS new_refs ON new_refs.commit_sha = commits_diffs.new_commit_sha LEFT JOIN refs AS old_refs ON old_refs.commit_sha = commits_diffs.old_commit_sha), _last_5_tags AS (SELECT DISTINCT /* distinct new_ref_id, old_ref_id */ SUBSTRING_INDEX(new_ref_id, ':', -1) AS new_ref_id, SUBSTRING_INDEX(old_ref_id, ':', -1) AS old_ref_id FROM refs_commits_diffs WHERE SUBSTRING_INDEX(new_ref_id, ':', 4) IN (${repo_id}) ORDER BY 1 DESC NULLS LAST LIMIT 5), _bugs AS (SELECT DISTINCT b.name, SUBSTRING_INDEX(rid.new_ref_id, 'tags/', -1) AS tag_name, i.issue_key AS issue_key, i.title, CAST(i.lead_time_minutes AS NUMERIC) / NULLIF(1440, 0) AS lead_time_in_days, CONCAT(b.url, '/', i.issue_key) AS url FROM refs_issues_diffs AS rid LEFT JOIN issues AS i ON rid.issue_id = i.id LEFT JOIN pull_request_issues AS pri ON i.id = pri.issue_id JOIN boards AS b ON SUBSTRING_INDEX(rid.new_ref_id, ':', 4) = b.id WHERE SUBSTRING_INDEX(rid.new_ref_id, ':', 4) IN (${repo_id}) AND /* and rid.new_ref_id in (SELECT new_ref_id FROM _last_5_tags) */ SUBSTRING_INDEX(rid.new_ref_id, ':', -1) IN (SELECT new_ref_id FROM _last_5_tags) AND i.type = 'BUG'), _bug_age_rank AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY tag_name ORDER BY lead_time_in_days DESC NULLS LAST) AS bug_age_rank FROM _bugs) SELECT name, tag_name, issue_key, title, lead_time_in_days, url FROM _bug_age_rank WHERE bug_age_rank <= 10 ORDER BY tag_name NULLS FIRST, lead_time_in_days DESC NULLS LAST"
    }
   ]
  },
  {
   "title": "5.5 Ratio of Outstanding Bugs [Queue Time > Mean]",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* Get the avg bug age in history */ WITH _avg_bug_age AS (SELECT type, AVG(lead_time_minutes) AS average_bug_age FROM issues LEFT JOIN board_issues AS bi ON issues.id = bi.issue_id WHERE type = 'BUG' AND status = 'DONE' AND bi.board_id = ANY(ARRAY[${repo_id}]::text[]) GROUP BY 1), _bug_queue_time AS (SELECT i.id, abg.average_bug_age, (EXTRACT(EPOCH FROM (NOW() - created_date))/60) AS queue_time, CASE WHEN (EXTRACT(EPOCH FROM (NOW() - created_date))/60) >= average_bug_age THEN \">=avg_bug_age\" ELSE \"<avg_bug_age\" END AS distribution FROM issues AS i LEFT JOIN _avg_bug_age AS abg ON i.type = abg.type WHERE i.type = 'BUG' AND status <> 'DONE') SELECT distribution, COUNT(*) AS bug_count FROM _bug_queue_time GROUP BY 1"
    }
   ]
  },
  {
   "title": "5.6 List of Outstanding Bugs [All Open Bugs]",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "/* Get the queue time of all backlog bugs */ SELECT b.name AS repo_name, i.issue_key AS issue_key, i.title, i.created_date, CAST(((EXTRACT(EPOCH FROM (NOW() - i.created_date))/60)) AS NUMERIC) / NULLIF(3600, 0) AS queue_time_in_days, CONCAT(b.url, '/', i.issue_key) AS url FROM issues AS i LEFT JOIN board_issues AS bi ON i.id = bi.issue_id LEFT JOIN boards AS b ON bi.board_id = b.id WHERE i.type = 'BUG' AND i.status <> 'DONE' AND b.id = ANY(ARRAY[${repo_id}]::text[]) ORDER BY queue_time_in_days DESC NULLS LAST"
    }
   ]
  },
  { "title": "Contribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "6.1 Number of New Commits Per Tag",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 58 },
   "targets": [
    {
     "rawSql": "/* Get the bug distribution in last 5 tags */ WITH refs_commits_diffs AS (SELECT new_refs.id AS new_ref_id, old_refs.id AS old_ref_id, commits_diffs.commit_sha, new_commit_sha, old_commit_sha FROM commits_diffs LEFT JOIN refs AS new_refs ON new_refs.commit_sha = commits_diffs.new_commit_sha LEFT JOIN refs AS old_refs ON old_refs.commit_sha = commits_diffs.old_commit_sha), _last_5_tags AS (SELECT DISTINCT /* distinct new_ref_id, old_ref_id */ SUBSTRING_INDEX(new_ref_id, ':', -1) AS new_ref_id, SUBSTRING_INDEX(old_ref_id, ':', -1) AS old_ref_id FROM refs_commits_diffs WHERE SUBSTRING_INDEX(new_ref_id, ':', 4) IN (${repo_id}) ORDER BY 1 DESC NULLS LAST LIMIT 10) SELECT SUBSTRING_INDEX(rcd.new_ref_id, 'refs/tags/', -1) AS tag_name, SUBSTRING_INDEX(rcd.old_ref_id, 'refs/tags/', -1) AS old_tag_name, COUNT(*) AS commit_count FROM refs_commits_diffs AS rcd LEFT JOIN commits AS c ON rcd.commit_sha = c.sha WHERE SUBSTRING_INDEX(rcd.new_ref_id, ':', 4) IN (${repo_id}) AND /* and rcd.new_ref_id in (select new_ref_id from _last_5_tags) */ SUBSTRING_INDEX(rcd.new_ref_id, ':', -1) IN (SELECT new_ref_id FROM _last_5_tags) GROUP BY 1, 2 ORDER BY 1 NULLS FIRST"
    }
   ]
  },
  {
   "title": "6.2 Commit List for Drill-Down [Last 5 Tags]",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 58 },
   "targets": [
    {
     "rawSql": "/* Get the bug distribution in last 5 tags */ WITH refs_commits_diffs AS (SELECT new_refs.id AS new_ref_id, old_refs.id AS old_ref_id, commits_diffs.commit_sha, new_commit_sha, old_commit_sha FROM commits_diffs LEFT JOIN refs AS new_refs ON new_refs.commit_sha = commits_diffs.new_commit_sha LEFT JOIN refs AS old_refs ON old_refs.commit_sha = commits_diffs.old_commit_sha), _last_5_tags AS (SELECT DISTINCT /* distinct new_ref_id, old_ref_id */ SUBSTRING_INDEX(new_ref_id, ':', -1) AS new_ref_id, SUBSTRING_INDEX(old_ref_id, ':', -1) AS old_ref_id FROM refs_commits_diffs WHERE SUBSTRING_INDEX(new_ref_id, ':', 4) IN (${repo_id}) ORDER BY 1 DESC NULLS LAST LIMIT 10) SELECT SUBSTRING_INDEX(rcd.new_ref_id, 'refs/tags/', -1) AS new_tag_name, SUBSTRING_INDEX(rcd.old_ref_id, 'refs/tags/', -1) AS compared_tag_name, c.sha, c.message, c.additions, c.deletions, c.author_name FROM refs_commits_diffs AS rcd LEFT JOIN commits AS c ON rcd.commit_sha = c.sha WHERE SUBSTRING_INDEX(rcd.new_ref_id, ':', 4) IN (${repo_id}) AND /* and rcd.new_ref_id in (select new_ref_id from _last_5_tags) */ SUBSTRING_INDEX(rcd.new_ref_id, ':', -1) IN (SELECT new_ref_id FROM _last_5_tags) ORDER BY 1 DESC NULLS LAST"
    }
   ]
  },
  {
   "title": "7.1 Work-Type Distribution [Last Tag]",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* Get the work-type distribution in the last 5 tags */ WITH refs_commits_diffs AS (SELECT new_refs.id AS new_ref_id, old_refs.id AS old_ref_id, commits_diffs.commit_sha, new_commit_sha, old_commit_sha FROM commits_diffs LEFT JOIN refs AS new_refs ON new_refs.commit_sha = commits_diffs.new_commit_sha LEFT JOIN refs AS old_refs ON old_refs.commit_sha = commits_diffs.old_commit_sha), _last_5_tags AS (SELECT DISTINCT /* distinct new_ref_id, old_ref_id */ SUBSTRING_INDEX(new_ref_id, ':', -1) AS new_ref_id, SUBSTRING_INDEX(old_ref_id, ':', -1) AS old_ref_id FROM refs_commits_diffs WHERE SUBSTRING_INDEX(new_ref_id, ':', 4) IN (${repo_id}) ORDER BY 1 DESC NULLS LAST LIMIT 1), _combine_pr AS (SELECT pull_request_id AS id, commit_sha, p.pull_request_key AS pull_request_key FROM pull_request_commits LEFT JOIN pull_requests AS p ON pull_request_commits.pull_request_id = p.id WHERE base_repo_id = ANY(ARRAY[${repo_id}]::text[]) UNION SELECT id, merge_commit_sha, pull_request_key AS commit_sha FROM pull_requests WHERE base_repo_id = ANY(ARRAY[${repo_id}]::text[])), _commit_count_of_pr AS (SELECT SUBSTRING_INDEX(rcd.new_ref_id, 'tags/', -1) AS tag_name, pr.id AS pull_request_id, COUNT(c.sha) AS pr_commit_count FROM refs_commits_diffs AS rcd LEFT JOIN commits AS c ON rcd.commit_sha = c.sha /* left join pull_request_commits prc on c.sha = prc.commit_sha */ LEFT JOIN _combine_pr AS pr ON c.sha = pr.commit_sha WHERE SUBSTRING_INDEX(rcd.new_ref_id, ':', 4) IN (${repo_id}) AND /* and rcd.new_ref_id in (SELECT new_ref_id FROM _last_5_tags) */ SUBSTRING_INDEX(rcd.new_ref_id, ':', -1) IN (SELECT new_ref_id FROM _last_5_tags) GROUP BY 1, 2), _pr_issues AS (SELECT pri.pull_request_id, pri.issue_id, i.issue_key, i.type, ROW_NUMBER() OVER (PARTITION BY issue_id ORDER BY pr.created_date ASC NULLS FIRST) AS pr_rank FROM pull_request_issues AS pri LEFT JOIN pull_requests AS pr ON pri.pull_request_id = pr.id LEFT JOIN issues AS i ON pri.issue_id = i.id WHERE i.issue_key <> 0), _final_results AS (SELECT DISTINCT ccop.*, pi.type FROM _commit_count_of_pr AS ccop LEFT JOIN _pr_issues AS pi ON ccop.pull_request_id = pi.pull_request_id WHERE pi.pr_rank = 1 ORDER BY 1 NULLS FIRST) SELECT tag_name, CASE WHEN type <> '' THEN type ELSE 'UNKNOWN' END AS type, SUM(pr_commit_count) AS commit_count FROM _final_results GROUP BY 1, 2"
    }
   ]
  },
  {
   "title": "7.2 Work-Type Distribution [The Tag before Last]",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* Get the work-type distribution in the last 5 tags */ WITH refs_commits_diffs AS (SELECT new_refs.id AS new_ref_id, old_refs.id AS old_ref_id, commits_diffs.commit_sha, new_commit_sha, old_commit_sha FROM commits_diffs LEFT JOIN refs AS new_refs ON new_refs.commit_sha = commits_diffs.new_commit_sha LEFT JOIN refs AS old_refs ON old_refs.commit_sha = commits_diffs.old_commit_sha), _last_5_tags AS (SELECT DISTINCT /* distinct new_ref_id, old_ref_id */ SUBSTRING_INDEX(new_ref_id, ':', -1) AS new_ref_id, SUBSTRING_INDEX(old_ref_id, ':', -1) AS old_ref_id FROM refs_commits_diffs WHERE SUBSTRING_INDEX(new_ref_id, ':', 4) IN (${repo_id}) ORDER BY 1 DESC NULLS LAST LIMIT 1 OFFSET 1), _combine_pr AS (SELECT pull_request_id AS id, commit_sha, p.pull_request_key AS pull_request_key FROM pull_request_commits LEFT JOIN pull_requests AS p ON pull_request_commits.pull_request_id = p.id WHERE base_repo_id = ANY(ARRAY[${repo_id}]::text[]) UNION SELECT id, merge_commit_sha, pull_request_key AS commit_sha FROM pull_requests WHERE base_repo_id = ANY(ARRAY[${repo_id}]::text[])), _commit_count_of_pr AS (SELECT SUBSTRING_INDEX(rcd.new_ref_id, 'tags/', -1) AS tag_name, pr.id AS pull_request_id, COUNT(c.sha) AS pr_commit_count FROM refs_commits_diffs AS rcd LEFT JOIN commits AS c ON rcd.commit_sha = c.sha /* left join pull_request_commits prc on c.sha = prc.commit_sha */ LEFT JOIN _combine_pr AS pr ON c.sha = pr.commit_sha WHERE SUBSTRING_INDEX(rcd.new_ref_id, ':', 4) IN (${repo_id}) AND /* and rcd.new_ref_id in (SELECT new_ref_id FROM _last_5_tags) */ SUBSTRING_INDEX(rcd.new_ref_id, ':', -1) IN (SELECT new_ref_id FROM _last_5_tags) GROUP BY 1, 2), _pr_issues AS (SELECT pri.pull_request_id, pri.issue_id, i.issue_key, i.type, ROW_NUMBER() OVER (PARTITION BY issue_id ORDER BY pr.created_date ASC NULLS FIRST) AS pr_rank FROM pull_request_issues AS pri LEFT JOIN pull_requests AS pr ON pri.pull_request_id = pr.id LEFT JOIN issues AS i ON pri.issue_id = i.id WHERE i.issue_key <> 0), _final_results AS (SELECT DISTINCT ccop.*, pi.type FROM _commit_count_of_pr AS ccop LEFT JOIN _pr_issues AS pi ON ccop.pull_request_id = pi.pull_request_id WHERE pi.pr_rank = 1 ORDER BY 1 NULLS FIRST) SELECT tag_name, CASE WHEN type <> '' THEN type ELSE 'UNKNOWN' END AS type, SUM(pr_commit_count) AS commit_count FROM _final_results GROUP BY 1, 2"
    }
   ]
  },
  {
   "title": "7.3 Work-Type Distribution [The 2nd Tag before Last]",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* Get the work-type distribution in the last 5 tags */ WITH refs_commits_diffs AS (SELECT new_refs.id AS new_ref_id, old_refs.id AS old_ref_id, commits_diffs.commit_sha, new_commit_sha, old_commit_sha FROM commits_diffs LEFT JOIN refs AS new_refs ON new_refs.commit_sha = commits_diffs.new_commit_sha LEFT JOIN refs AS old_refs ON old_refs.commit_sha = commits_diffs.old_commit_sha), _last_5_tags AS (SELECT DISTINCT /* distinct new_ref_id, old_ref_id */ SUBSTRING_INDEX(new_ref_id, ':', -1) AS new_ref_id, SUBSTRING_INDEX(old_ref_id, ':', -1) AS old_ref_id FROM refs_commits_diffs WHERE SUBSTRING_INDEX(new_ref_id, ':', 4) IN (${repo_id}) ORDER BY 1 DESC NULLS LAST LIMIT 1 OFFSET 2), _combine_pr AS (SELECT pull_request_id AS id, commit_sha, p.pull_request_key AS pull_request_key FROM pull_request_commits LEFT JOIN pull_requests AS p ON pull_request_commits.pull_request_id = p.id WHERE base_repo_id = ANY(ARRAY[${repo_id}]::text[]) UNION SELECT id, merge_commit_sha, pull_request_key AS commit_sha FROM pull_requests WHERE base_repo_id = ANY(ARRAY[${repo_id}]::text[])), _commit_count_of_pr AS (SELECT SUBSTRING_INDEX(rcd.new_ref_id, 'tags/', -1) AS tag_name, pr.id AS pull_request_id, COUNT(c.sha) AS pr_commit_count FROM refs_commits_diffs AS rcd LEFT JOIN commits AS c ON rcd.commit_sha = c.sha /* left join pull_request_commits prc on c.sha = prc.commit_sha */ LEFT JOIN _combine_pr AS pr ON c.sha = pr.commit_sha WHERE SUBSTRING_INDEX(rcd.new_ref_id, ':', 4) IN (${repo_id}) AND /* and rcd.new_ref_id in (SELECT new_ref_id FROM _last_5_tags) */ SUBSTRING_INDEX(rcd.new_ref_id, ':', -1) IN (SELECT new_ref_id FROM _last_5_tags) GROUP BY 1, 2), _pr_issues AS (SELECT pri.pull_request_id, pri.issue_id, i.issue_key, i.type, ROW_NUMBER() OVER (PARTITION BY issue_id ORDER BY pr.created_date ASC NULLS FIRST) AS pr_rank FROM pull_request_issues AS pri LEFT JOIN pull_requests AS pr ON pri.pull_request_id = pr.id LEFT JOIN issues AS i ON pri.issue_id = i.id WHERE i.issue_key <> 0), _final_results AS (SELECT DISTINCT ccop.*, pi.type FROM _commit_count_of_pr AS ccop LEFT JOIN _pr_issues AS pi ON ccop.pull_request_id = pi.pull_request_id WHERE pi.pr_rank = 1 ORDER BY 1 NULLS FIRST) SELECT tag_name, CASE WHEN type <> '' THEN type ELSE 'UNKNOWN' END AS type, SUM(pr_commit_count) AS commit_count FROM _final_results GROUP BY 1, 2"
    }
   ]
  },
  {
   "title": "8.1 Committers Contributing 80%+ Commits [Last 5 Tags]",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "select": [
      [
       { "params": [ "id" ], "type": "column" }
      ]
     ],
     "table": "ae_projects",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "8.2 Top Contributors [Last 5 Tags]",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 72 },
   "targets": [
    {
     "rawSql": "WITH refs_commits_diffs AS (SELECT new_refs.id AS new_ref_id, old_refs.id AS old_ref_id, commits_diffs.commit_sha, new_commit_sha, old_commit_sha FROM commits_diffs LEFT JOIN refs AS new_refs ON new_refs.commit_sha = commits_diffs.new_commit_sha LEFT JOIN refs AS old_refs ON old_refs.commit_sha = commits_diffs.old_commit_sha), _last_5_tags AS (SELECT DISTINCT /* distinct new_ref_id, old_ref_id */ SUBSTRING_INDEX(new_ref_id, ':', -1) AS new_ref_id, SUBSTRING_INDEX(old_ref_id, ':', -1) AS old_ref_id FROM refs_commits_diffs WHERE SUBSTRING_INDEX(new_ref_id, ':', 4) IN (${repo_id}) ORDER BY 1 DESC NULLS LAST LIMIT 5) SELECT c.author_name, COUNT(c.sha) AS total_dev_eq FROM refs_commits_diffs AS rcf LEFT JOIN commits AS c ON rcf.commit_sha = c.sha WHERE SUBSTRING_INDEX(rcf.new_ref_id, ':', 4) /* rcf.new_ref_id in (SELECT new_ref_id FROM _last_5_tags) */ IN (${repo_id}) AND SUBSTRING_INDEX(rcf.new_ref_id, ':', -1) IN (SELECT new_ref_id FROM _last_5_tags) GROUP BY 1 ORDER BY 2 DESC NULLS LAST LIMIT 10"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 79 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   },
   "targets": [
    {}
   ]
  }
 ]
}