{
 "title": "PagerDuty",
 "tags": [
  "Data Source Dashboard",
  "Stable Data Sources"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "board_id",
    "label": "Choose Board",
    "query": "SELECT name || '--' || id FROM boards WHERE id LIKE 'pagerduty%'"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard shows the incident data from PagerDuty.\n- Data Source Required: PagerDuty"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "1. Incident Resolution Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Incidents [Created in Selected Time Range]",
   "type": "stat",
   "description": "1. Total number of incidents created.\n2. The requirements being calculated are filtered by \"requirement creation time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT i.id) AS value FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id WHERE $__timeFilter(i.created_date) AND bi.board_id::text IN (SELECT v FROM unnest(CASE WHEN '${board_id}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${board_id}]::text[] END) v)"
    }
   ]
  },
  {
   "title": "Number of Resolved Incidents [Created in Selected Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT i.id) AS value FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id WHERE i.original_status = 'resolved' AND $__timeFilter(i.created_date) AND bi.board_id::text IN (SELECT v FROM unnest(CASE WHEN '${board_id}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${board_id}]::text[] END) v)"
    }
   ]
  },
  {
   "title": "List of Incidents [Created in Selected Time Range]",
   "type": "table",
   "description": "1. Total number of incidents created.\n2. The requirements being calculated are filtered by \"requirement creation time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT b.name AS service, i.issue_key, i.description, i.original_status, i.priority, i.created_date, i.updated_date, ROUND(CAST((CAST(i.lead_time_minutes AS NUMERIC) / NULLIF(1440, 0)) AS DECIMAL), 1) AS lead_time_days, i.url FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE $__timeFilter(i.created_date) AND bi.board_id::text IN (SELECT v FROM unnest(CASE WHEN '${board_id}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${board_id}]::text[] END) v)"
    }
   ]
  },
  {
   "title": "Incident Resolution Rate [Incidents created in the selected time range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _requirements AS (SELECT COUNT(DISTINCT i.id) AS total_count, COUNT(DISTINCT CASE WHEN i.original_status = 'resolved' THEN i.id ELSE NULL END) AS resolved_count FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id WHERE $__timeFilter(i.created_date) AND bi.board_id::text IN (SELECT v FROM unnest(CASE WHEN '${board_id}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${board_id}]::text[] END) v)) SELECT NOW() AS time, CAST(1.0 * resolved_count AS NUMERIC) / NULLIF(total_count, 0) AS requirement_delivery_rate FROM _requirements"
    }
   ]
  },
  {
   "title": "Incident Resolution Rate over Time [Incidents Created in Selected Time Range]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH _requirements AS (SELECT CAST(i.created_date AS DATE) + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST(i.created_date AS DATE)) + 1) AS time, CAST(1.0 * COUNT(DISTINCT CASE WHEN i.original_status = 'resolved' THEN i.id ELSE NULL END) AS NUMERIC) / NULLIF(COUNT(DISTINCT i.id), 0) AS resolved_rate FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id WHERE $__timeFilter(i.created_date) AND bi.board_id::text IN (SELECT v FROM unnest(CASE WHEN '${board_id}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${board_id}]::text[] END) v) GROUP BY 1) SELECT time, resolved_rate FROM _requirements ORDER BY time NULLS FIRST"
    }
   ]
  },
  {
   "title": "2. Mean Time to Resolve (MTTR)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MTTR [Incidents Resolved in Select Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(CAST(lead_time_minutes AS NUMERIC) / NULLIF(1440, 0)) AS value FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id WHERE i.original_status = 'resolved' AND $__timeFilter(i.resolution_date) AND bi.board_id::text IN (SELECT v FROM unnest(CASE WHEN '${board_id}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${board_id}]::text[] END) v)"
    }
   ]
  },
  {
   "title": "80% Incidents' MTTR are less than # [Incidents Resolved in Select Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _ranks AS (SELECT i.lead_time_minutes, PERCENT_RANK() OVER (ORDER BY lead_time_minutes ASC NULLS FIRST) AS ranks FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id WHERE i.original_status = 'resolved' AND $__timeFilter(i.resolution_date) AND bi.board_id::text IN (SELECT v FROM unnest(CASE WHEN '${board_id}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${board_id}]::text[] END) v)) SELECT MAX(CAST(lead_time_minutes AS NUMERIC) / NULLIF(1440, 0)) AS value FROM _ranks WHERE ranks <= 0.8"
    }
   ]
  },
  {
   "title": "Mean MTTR [Incidents Resolved in Select Time Range]",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH _requirements AS (SELECT CAST(i.resolution_date AS DATE) + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST(i.resolution_date AS DATE)) + 1) AS time, AVG(CAST(lead_time_minutes AS NUMERIC) / NULLIF(1440, 0)) AS mean_incident_age FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id WHERE i.original_status = 'resolved' AND $__timeFilter(i.resolution_date) AND bi.board_id::text IN (SELECT v FROM unnest(CASE WHEN '${board_id}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${board_id}]::text[] END) v) GROUP BY 1) SELECT TO_CHAR(CAST(time AS TIMESTAMP), 'FMMonth YYYY') AS month, mean_incident_age FROM _requirements ORDER BY time ASC NULLS FIRST"
    }
   ]
  },
  {
   "title": "Cumulative Distribution of MTTR [Incidents Resolved in Select Time Range]",
   "type": "graph",
   "description": "1. The cumulative distribution of MTTR\n2. Each point refers to the percent rank of a distinct duration to resolve incidents.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent Rank (%)" }
   ],
   "targets": [
    {
     "rawSql": "WITH _ranks AS (SELECT ROUND(CAST(i.lead_time_minutes AS NUMERIC) / NULLIF(1440, 0)) AS lead_time_day FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id WHERE i.original_status = 'resolved' AND $__timeFilter(i.resolution_date) AND bi.board_id::text IN (SELECT v FROM unnest(CASE WHEN '${board_id}' = '' THEN ARRAY[NULL::text] ELSE ARRAY[${board_id}]::text[] END) v) ORDER BY lead_time_day ASC NULLS FIRST) SELECT NOW() AS time, LPAD(lead_time_day || 'd', 4, ' ') AS metric, PERCENT_RANK() OVER (ORDER BY lead_time_day ASC NULLS FIRST) AS value FROM _ranks ORDER BY lead_time_day ASC NULLS FIRST"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   },
   "targets": [
    {}
   ]
  }
 ]
}