{
 "title": "SonarQube Cloud (PostgreSQL)",
 "tags": [
  "Data Source Dashboard",
  "Stable Data Sources"
 ],
 "time": { "from": "now", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_id",
    "label": "SonarQube Project",
    "query": "select concat(name, '--', id) as text from cq_projects"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "select distinct severity from cq_issues where id like 'sonar%'"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard shows the code quality metrics from SonarCloud.\n- Data Source Required: SonarCloud\n- This dashboard does not honor the time filter on the top-right side as SonarQube metrics are all from the latest scan."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Software Quality",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Security",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT COUNT(DISTINCT ci.id) FROM cq_issues AS ci JOIN cq_issue_impacts AS cii ON ci.id = cii.cq_issue_id WHERE ci.project_key = ANY(ARRAY[${project_id}]::text[]) AND cii.software_quality = 'SECURITY' AND ci.severity = ANY(ARRAY[${severity}]::text[])"
    }
   ]
  },
  {
   "title": "Reliability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT COUNT(DISTINCT ci.id) FROM cq_issues AS ci JOIN cq_issue_impacts AS cii ON ci.id = cii.cq_issue_id WHERE ci.project_key = ANY(ARRAY[${project_id}]::text[]) AND cii.software_quality = 'RELIABILITY' AND ci.severity = ANY(ARRAY[${severity}]::text[])"
    }
   ]
  },
  {
   "title": "Maintainability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT COUNT(DISTINCT ci.id) FROM cq_issues AS ci JOIN cq_issue_impacts AS cii ON ci.id = cii.cq_issue_id WHERE ci.project_key = ANY(ARRAY[${project_id}]::text[]) AND cii.software_quality = 'MAINTAINABILITY' AND ci.severity = ANY(ARRAY[${severity}]::text[])"
    }
   ]
  },
  { "title": "Security Review", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Security Hotspots",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT COUNT(DISTINCT id) AS 'Security Hotspots' FROM cq_issues WHERE project_key = ANY(ARRAY[${project_id}]::text[]) AND type = 'HOTSPOTS' AND severity = ANY(ARRAY[${severity}]::text[])"
    }
   ]
  },
  {
   "title": "Hotspots Reviewed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT CONCAT(ROUND(CAST(COUNT(CASE WHEN status <> 'TO_REVIEW' THEN id ELSE NULL END) AS NUMERIC) / NULLIF(COUNT(DISTINCT id), 0) * 100, 2), '%') AS 'Reviewed' FROM cq_issues WHERE project_key = ANY(ARRAY[${project_id}]::text[]) AND type = 'HOTSPOTS' AND severity = ANY(ARRAY[${severity}]::text[])"
    }
   ]
  },
  {
   "title": "Test & Maintainability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Test Coverage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT CONCAT(ROUND(CAST((SUM(lines_to_cover) - SUM(uncovered_lines)) AS NUMERIC) / NULLIF(SUM(lines_to_cover), 0) * 100, 1), '% ', 'Coverage on ', ROUND(CAST(SUM(lines_to_cover) AS NUMERIC) / NULLIF(1000, 0), 0), 'k Lines to cover') FROM cq_file_metrics WHERE project_key = ANY(ARRAY[${project_id}]::text[])"
    }
   ]
  },
  {
   "title": "Maintainability - Code Smells",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "code smells" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT COUNT(DISTINCT id) AS 'Code Smells' FROM cq_issues WHERE project_key = ANY(ARRAY[${project_id}]::text[]) AND type = 'CODE_SMELL' AND severity = ANY(ARRAY[${severity}]::text[])"
    }
   ]
  },
  {
   "title": "Maintainability - Debt",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT CONCAT(FLOOR(CAST(CAST(SUM(debt) AS NUMERIC) / NULLIF(8, 0) AS NUMERIC) / NULLIF(60, 0)), \" day(s) \", FLOOR(CAST((SUM(debt) % 480) AS NUMERIC) / NULLIF(60, 0)), \" hour(s) \") AS 'Debt' FROM cq_issues WHERE project_key = ANY(ARRAY[${project_id}]::text[]) AND type = 'CODE_SMELL' AND severity = ANY(ARRAY[${severity}]::text[])"
    }
   ]
  },
  {
   "title": "Duplications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Duplicated Blocks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT SUM(duplicated_blocks) FROM cq_file_metrics WHERE project_key = ANY(ARRAY[${project_id}]::text[])"
    }
   ]
  },
  {
   "title": "Duplicated Lines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT CONCAT(ROUND(CAST(SUM(duplicated_lines) AS NUMERIC) / NULLIF(SUM(num_of_lines), 0) * 100, 1), '% ', 'Duplications on ', ROUND(CAST(SUM(ncloc) AS NUMERIC) / NULLIF(1000, 0), 0), 'k Lines') FROM cq_file_metrics WHERE project_key = ANY(ARRAY[${project_id}]::text[])"
    }
   ]
  },
  { "title": "Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Lines of Code",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT SUM(ncloc) FROM cq_file_metrics WHERE project_key = ANY(ARRAY[${project_id}]::text[])"
    }
   ]
  },
  {
   "title": "Lines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT SUM(num_of_lines) FROM cq_file_metrics WHERE project_key = ANY(ARRAY[${project_id}]::text[])"
    }
   ]
  },
  {
   "title": "Files",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT COUNT(DISTINCT file_path) FROM cq_file_metrics WHERE project_key = ANY(ARRAY[${project_id}]::text[])"
    }
   ]
  },
  { "title": "Overall Code Quality Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Code Quality Metrics by Files (Top 20 order by Bugs)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT file_name, num_of_lines AS 'Lines of Code', bugs AS 'Bugs', vulnerabilities AS 'Vulnerabilities', code_smells AS 'Code Smells', security_hotspots AS 'Security Hotspots', CONCAT(ROUND(coverage, 2), '%') AS 'Coverage', CONCAT(ROUND(duplicated_lines_density, 2), '%') AS 'Duplications' FROM cq_file_metrics WHERE project_key = ANY(ARRAY[${project_id}]::text[]) ORDER BY bugs DESC NULLS LAST LIMIT 20"
    }
   ]
  }
 ]
}