{
 "title": "Teambition (PostgreSQL)",
 "tags": [ "Data Source Dashboard" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "board_id",
    "label": "Choose Board",
    "query": "select concat(name, '--', id) from boards where id like 'teambition%'"
   },
   {
    "name": "type",
    "label": "Issue Type",
    "query": "select distinct type from issues"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard shows the basic project management metrics from Teambition.\n- Data Source Required: Teambition"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "1. Issue Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Issues [Issues Created in Selected Time Range]",
   "type": "stat",
   "description": "1. Total number of issues created.\n2. The requirements being calculated are filtered by \"requirement creation time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT i.id) AS value FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id WHERE i.type = ANY(ARRAY[${type}]::text[]) AND $__timeFilter(i.created_date) AND bi.board_id = ANY(ARRAY[${board_id}]::text[])"
    }
   ]
  },
  {
   "title": "Number of Delivered Issue [Issues Created in Selected Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT i.id) AS value FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id WHERE i.type = ANY(ARRAY[${type}]::text[]) AND i.status = 'DONE' AND $__timeFilter(i.created_date) AND bi.board_id = ANY(ARRAY[${board_id}]::text[])"
    }
   ]
  },
  {
   "title": "Issue Status Distribution over Month [Issues Created in Selected Time Range]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT CAST(i.created_date AS DATE) + INTERVAL '1 day' AS time, COUNT(DISTINCT CASE WHEN status <> 'DONE' THEN i.id ELSE NULL END) AS \"Number of Open Issues\", COUNT(DISTINCT CASE WHEN status = 'DONE' THEN i.id ELSE NULL END) AS \"Number of Delivered Issues\" FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE i.type = ANY(ARRAY[${type}]::text[]) AND $__timeFilter(i.created_date) AND bi.board_id = ANY(ARRAY[${board_id}]::text[]) GROUP BY 1"
    }
   ]
  },
  {
   "title": "Issue Delivery Rate [Issues Created in Selected Time Range]",
   "type": "stat",
   "description": "Issue Delivery Rate = count(Delivered Issues)/count(Issues)",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _requirements AS (SELECT COUNT(DISTINCT i.id) AS total_count, COUNT(DISTINCT CASE WHEN i.status = 'DONE' THEN i.id ELSE NULL END) AS delivered_count FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id WHERE i.type = ANY(ARRAY[${type}]::text[]) AND $__timeFilter(i.created_date) AND bi.board_id = ANY(ARRAY[${board_id}]::text[])) SELECT NOW() AS time, CAST(1.0 * delivered_count AS NUMERIC) / NULLIF(total_count, 0) AS requirement_delivery_rate FROM _requirements"
    }
   ]
  },
  {
   "title": "Issue Delivery Rate over Time [Issues Created in Selected Time Range]",
   "type": "timeseries",
   "description": "Issue Delivery Rate = count(Delivered Issues)/count(Issues)",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH _requirements AS (SELECT CAST(i.created_date AS DATE) + INTERVAL '1 day' AS time, CAST(1.0 * COUNT(DISTINCT CASE WHEN i.status = 'DONE' THEN i.id ELSE NULL END) AS NUMERIC) / NULLIF(COUNT(DISTINCT i.id), 0) AS delivered_rate FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id WHERE i.type = ANY(ARRAY[${type}]::text[]) AND $__timeFilter(i.created_date) AND bi.board_id = ANY(ARRAY[${board_id}]::text[]) GROUP BY 1) SELECT time, delivered_rate FROM _requirements ORDER BY time NULLS FIRST"
    }
   ]
  },
  {
   "title": "2. Issue Lead Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mean Issue Lead Time in Days [Issues Resolved in Select Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(CAST(lead_time_minutes AS NUMERIC) / NULLIF(1440, 0)) AS value FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id WHERE i.type = ANY(ARRAY[${type}]::text[]) AND i.status = 'DONE' AND $__timeFilter(i.resolution_date) AND bi.board_id = ANY(ARRAY[${board_id}]::text[])"
    }
   ]
  },
  {
   "title": "80% Issues' Lead Time are less than # days [Issues Resolved in Select Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _ranks AS (SELECT i.lead_time_minutes, PERCENT_RANK() OVER (ORDER BY lead_time_minutes ASC NULLS FIRST) AS ranks FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id WHERE i.type = ANY(ARRAY[${type}]::text[]) AND i.status = 'DONE' AND $__timeFilter(i.resolution_date) AND bi.board_id = ANY(ARRAY[${board_id}]::text[])) SELECT MAX(CAST(lead_time_minutes AS NUMERIC) / NULLIF(1440, 0)) AS value FROM _ranks WHERE ranks <= 0.8"
    }
   ]
  },
  {
   "title": "Mean Issue Lead Time [Issues Resolved in Select Time Range]",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH _requirements AS (SELECT CAST(i.resolution_date AS DATE) + INTERVAL '1 day' AS time, AVG(CAST(lead_time_minutes AS NUMERIC) / NULLIF(1440, 0)) AS mean_lead_time FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id WHERE i.type = ANY(ARRAY[${type}]::text[]) AND i.status = 'DONE' AND $__timeFilter(i.resolution_date) AND bi.board_id = ANY(ARRAY[${board_id}]::text[]) GROUP BY 1) SELECT TO_CHAR(time, '%M %Y') AS month, mean_lead_time FROM _requirements ORDER BY time ASC NULLS FIRST"
    }
   ]
  },
  {
   "title": "Cumulative Distribution of Requirement Lead Time [Issues Resolved in Select Time Range]",
   "type": "graph",
   "description": "1. The cumulative distribution of requirement lead time. \n2. Each point refers to the percent rank of a lead time.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent Rank (%)" }
   ],
   "targets": [
    {
     "rawSql": "WITH _ranks AS (SELECT ROUND(CAST(i.lead_time_minutes AS NUMERIC) / NULLIF(1440, 0)) AS lead_time_day FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id WHERE i.type = ANY(ARRAY[${type}]::text[]) AND i.status = 'DONE' AND $__timeFilter(i.resolution_date) AND bi.board_id = ANY(ARRAY[${board_id}]::text[]) ORDER BY lead_time_day ASC NULLS FIRST) SELECT NOW() AS time, LPAD(CONCAT(lead_time_day, 'd'), 4, ' ') AS metric, PERCENT_RANK() OVER (ORDER BY lead_time_day ASC NULLS FIRST) AS value FROM _ranks ORDER BY lead_time_day ASC NULLS FIRST"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   },
   "targets": [
    {}
   ]
  }
 ]
}