{
 "title": "Work Logs (PostgreSQL)",
 "tags": [
  "Developer",
  "Highlights",
  "New"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "team",
    "label": "Team",
    "query": "select concat(name, '--', id) from teams"
   },
   {
    "name": "users",
    "label": "User",
    "query": "select concat(users.name, '--', users.id) from users left join team_users on users.id = team_users.user_id where team_users.team_id in ($team)"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard shows the work logs of a team or a developer\n- Data Sources Required to show all data: \n   - One of the Git tools, e.g. [GitHub](https://devlake.apache.org/docs/Configuration/GitHub), [GitLab](https://devlake.apache.org/docs/Configuration/GitLab), [Bitbucket](https://devlake.apache.org/docs/Configuration/BitBucket) or [Azure DevOps](https://devlake.apache.org/docs/Configuration/AzureDevOps)\n   - One of the issue tracking tools, e.g. [Jira](https://devlake.apache.org/docs/Configuration/Jira)\n   - You also need to complete the [team configuration](https://devlake.apache.org/docs/Configuration/TeamConfiguration) to use this dashboard"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Worklogs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Activities by date",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "WITH _accounts AS (SELECT ua.account_id, ua.user_id, u.name FROM accounts AS a JOIN user_accounts AS ua ON a.id = ua.account_id JOIN users AS u ON ua.user_id = u.id WHERE ua.user_id IN ($users)), _activities AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY \"Date\" ORDER BY \"Time\" DESC NULLS LAST) AS _row_number FROM (SELECT TO_CHAR(created_date, '%Y-%m-%d | %W') AS Date, created_date AS Time, 'Create an issue' AS Activity, CONCAT('#', issue_key, ' ', title) AS Details, a.name AS Name FROM issues AS i JOIN _accounts AS a ON i.creator_id = a.account_id WHERE $__timeFilter(created_date) UNION SELECT TO_CHAR(resolution_date, '%Y-%m-%d | %W') AS Date, resolution_date AS Time, 'Issue resolved' AS Activity, CONCAT('#', issue_key, ' ', title) AS Details, a.name AS Name FROM issues AS i JOIN _accounts AS a ON i.assignee_id = a.account_id WHERE $__timeFilter(resolution_date) UNION SELECT TO_CHAR(authored_date, '%Y-%m-%d | %W') AS Date, authored_date AS Time, 'Finish a commit' AS Activity, CONCAT(message, ' #', sha) AS Details, a.name AS Name FROM commits AS c JOIN _accounts AS a ON c.author_id = a.account_id WHERE $__timeFilter(authored_date) UNION SELECT TO_CHAR(created_date, '%Y-%m-%d | %W') AS Date, created_date AS Time, 'Open a PR' AS Activity, CONCAT('#', pull_request_key, ' ', title) AS Details, a.name AS Name FROM pull_requests AS pr JOIN _accounts AS a ON pr.author_id = a.account_id WHERE $__timeFilter(created_date) UNION SELECT TO_CHAR(merged_date, '%Y-%m-%d | %W') AS Date, merged_date AS Time, 'PR gets merged' AS Activity, CONCAT('#', pull_request_key, ' ', title) AS Details, a.name AS Name FROM pull_requests AS pr JOIN _accounts AS a ON pr.author_id = a.account_id WHERE $__timeFilter(merged_date) UNION SELECT TO_CHAR(prc.created_date, '%Y-%m-%d | %W') AS Date, prc.created_date AS Time, 'Comment on PR' AS Activity, CONCAT('#', pr.pull_request_key, ' ', pr.title) AS Details, a.name AS Name FROM pull_request_comments AS prc LEFT JOIN pull_requests AS pr ON prc.pull_request_id = pr.id JOIN _accounts AS a ON prc.account_id = a.account_id WHERE prc.type = 'NORMAL' AND $__timeFilter(prc.created_date) UNION SELECT TO_CHAR(prc.created_date, '%Y-%m-%d | %W') AS Date, prc.created_date AS Time, 'Review PR' AS Activity, CONCAT('#', pr.pull_request_key, ' ', pr.title) AS Details, a.name AS Name FROM pull_request_comments AS prc LEFT JOIN pull_requests AS pr ON prc.pull_request_id = pr.id JOIN _accounts AS a ON prc.account_id = a.account_id WHERE prc.type IN ('REVIEW', 'DIFF') AND $__timeFilter(prc.created_date)) AS t ORDER BY Time DESC NULLS LAST) SELECT CASE WHEN _row_number = 1 THEN 'Date' ELSE NULL END AS \"Date\", \"Time\", Activity, Details, Name FROM _activities"
    }
   ]
  },
  {
   "title": "Activity count in the last year",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "WITH _accounts AS (SELECT ua.account_id, ua.user_id, u.name FROM accounts AS a JOIN user_accounts AS ua ON a.id = ua.account_id JOIN users AS u ON ua.user_id = u.id WHERE ua.user_id IN ($users)), _activities AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY \"Date\" ORDER BY \"Time\" DESC NULLS LAST) AS _row_number FROM (SELECT CAST(created_date AS DATE) AS Date, created_date AS Time, 'Create an issue' AS Activity, CONCAT('#', issue_key, ' ', title) AS Details, a.name AS Name FROM issues AS i JOIN _accounts AS a ON i.creator_id = a.account_id WHERE $__timeFilter(created_date) UNION SELECT CAST(resolution_date AS DATE) AS Date, resolution_date AS Time, 'Issue resolved' AS Activity, CONCAT('#', issue_key, ' ', title) AS Details, a.name AS Name FROM issues AS i JOIN _accounts AS a ON i.assignee_id = a.account_id WHERE $__timeFilter(resolution_date) UNION SELECT CAST(authored_date AS DATE) AS Date, authored_date AS Time, 'Finish a commit' AS Activity, CONCAT(message, ' #', sha) AS Details, a.name AS Name FROM commits AS c JOIN _accounts AS a ON c.author_id = a.account_id WHERE $__timeFilter(authored_date) UNION SELECT CAST(created_date AS DATE) AS Date, created_date AS Time, 'Open a PR' AS Activity, CONCAT('#', pull_request_key, ' ', title) AS Details, a.name AS Name FROM pull_requests AS pr JOIN _accounts AS a ON pr.author_id = a.account_id WHERE $__timeFilter(created_date) UNION SELECT CAST(merged_date AS DATE) AS Date, merged_date AS Time, 'PR gets merged' AS Activity, CONCAT('#', pull_request_key, ' ', title) AS Details, a.name AS Name FROM pull_requests AS pr JOIN _accounts AS a ON pr.author_id = a.account_id WHERE $__timeFilter(merged_date) UNION SELECT CAST(prc.created_date AS DATE) AS Date, prc.created_date AS Time, 'Comment on PR' AS Activity, CONCAT('#', pr.pull_request_key, ' ', pr.title) AS Details, a.name AS Name FROM pull_request_comments AS prc LEFT JOIN pull_requests AS pr ON prc.pull_request_id = pr.id JOIN _accounts AS a ON prc.account_id = a.account_id WHERE prc.type = 'NORMAL' AND $__timeFilter(prc.created_date) UNION SELECT CAST(prc.created_date AS DATE) AS Date, prc.created_date AS Time, 'Review PR' AS Activity, CONCAT('#', pr.pull_request_key, ' ', pr.title) AS Details, a.name AS Name FROM pull_request_comments AS prc LEFT JOIN pull_requests AS pr ON prc.pull_request_id = pr.id JOIN _accounts AS a ON prc.account_id = a.account_id WHERE prc.type IN ('REVIEW', 'DIFF') AND $__timeFilter(prc.created_date)) AS t ORDER BY Time DESC NULLS LAST), _activity_count_per_day AS (SELECT Date, COUNT(*) AS value FROM _activities GROUP BY 1), last_few_calendar_months AS (/* construct the last few calendar months within the selected time period in the top-right corner */ SELECT CAST(($__timeTo()::timestamp - INTERVAL '1 day') AS DATE) AS d, TO_CHAR(CAST(($__timeTo()::timestamp - INTERVAL '1 day') AS DATE), 'w%u %Y') AS week_name, TO_CHAR(CAST(($__timeTo()::timestamp - INTERVAL '1 day') AS DATE), '%Y%u') AS week_number FROM (SELECT 0 AS H UNION ALL SELECT 100 UNION ALL SELECT 200 UNION ALL SELECT 300) AS H CROSS JOIN (SELECT 0 AS T UNION ALL SELECT 10 UNION ALL SELECT 20 UNION ALL SELECT 30 UNION ALL SELECT 40 UNION ALL SELECT 50 UNION ALL SELECT 60 UNION ALL SELECT 70 UNION ALL SELECT 80 UNION ALL SELECT 90) AS T CROSS JOIN (SELECT 0 AS U UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS U WHERE ($__timeTo()::timestamp - INTERVAL '1 day') > $__timeFrom()), _calendar_months_with_rank AS (SELECT d, CONCAT(week_name, ' (', TO_CHAR(d - INTERVAL 'WEEKDAY DAY', '%m/%d'), ' ~ ', TO_CHAR(d - INTERVAL 'WEEKDAY DAY' + INTERVAL '6 DAY', '%m/%d'), ')') AS week_name, week_number, TO_CHAR(d, '%W') AS weekday, DENSE_RANK() OVER (ORDER BY week_number DESC NULLS LAST) AS week_rank FROM last_few_calendar_months ORDER BY 1 DESC NULLS LAST), _final_dataset AS (SELECT _calendar_months_with_rank.*, CASE WHEN _activity_count_per_day.value IS NULL THEN 0 ELSE _activity_count_per_day.value END AS activity_count FROM _calendar_months_with_rank LEFT JOIN _activity_count_per_day ON _calendar_months_with_rank.d = _activity_count_per_day.Date), WeekSummary AS (SELECT week_name, SUM(CASE WHEN weekday = 'Monday' THEN activity_count END) AS Mon, SUM(CASE WHEN weekday = 'Tuesday' THEN activity_count END) AS Tue, SUM(CASE WHEN weekday = 'Wednesday' THEN activity_count END) AS Wed, SUM(CASE WHEN weekday = 'Thursday' THEN activity_count END) AS Thur, SUM(CASE WHEN weekday = 'Friday' THEN activity_count END) AS Fri, SUM(CASE WHEN weekday = 'Saturday' THEN activity_count END) AS Sat, SUM(CASE WHEN weekday = 'Sunday' THEN activity_count END) AS Sun FROM _final_dataset WHERE week_rank BETWEEN 1 AND 52 GROUP BY week_name) SELECT week_name, Mon, Tue, Wed, Thur, Fri, Sat, Sun FROM WeekSummary ORDER BY CAST(SUBSTRING(week_name FROM STRPOS(week_name, ' ') + 1 FOR 4) AS UBIGINT) DESC NULLS LAST, CAST(SUBSTRING(week_name FROM 2 FOR STRPOS(week_name, ' ') - 2) AS UBIGINT) DESC NULLS LAST"
    }
   ]
  },
  {
   "title": "Activity distribution in last 7 days",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 21 },
   "targets": [
    {
     "rawSql": "WITH _accounts AS (SELECT ua.account_id, ua.user_id, u.name FROM accounts AS a JOIN user_accounts AS ua ON a.id = ua.account_id JOIN users AS u ON ua.user_id = u.id WHERE ua.user_id IN ($users)), _activities AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY \"Date\" ORDER BY \"Time\" DESC NULLS LAST) AS _row_number FROM (SELECT CAST(created_date AS DATE) AS Date, created_date AS Time, 'Create an issue' AS Activity, CONCAT('#', issue_key, ' ', title) AS Details, a.name AS Name FROM issues AS i JOIN _accounts AS a ON i.creator_id = a.account_id WHERE $__timeFilter(created_date) UNION SELECT CAST(resolution_date AS DATE) AS Date, resolution_date AS Time, 'Issue resolved' AS Activity, CONCAT('#', issue_key, ' ', title) AS Details, a.name AS Name FROM issues AS i JOIN _accounts AS a ON i.assignee_id = a.account_id WHERE $__timeFilter(resolution_date) UNION SELECT CAST(authored_date AS DATE) AS Date, authored_date AS Time, 'Finish a commit' AS Activity, CONCAT(message, ' #', sha) AS Details, a.name AS Name FROM commits AS c JOIN _accounts AS a ON c.author_id = a.account_id WHERE $__timeFilter(authored_date) UNION SELECT CAST(created_date AS DATE) AS Date, created_date AS Time, 'Open a PR' AS Activity, CONCAT('#', pull_request_key, ' ', title) AS Details, a.name AS Name FROM pull_requests AS pr JOIN _accounts AS a ON pr.author_id = a.account_id WHERE $__timeFilter(created_date) UNION SELECT CAST(merged_date AS DATE) AS Date, merged_date AS Time, 'PR gets merged' AS Activity, CONCAT('#', pull_request_key, ' ', title) AS Details, a.name AS Name FROM pull_requests AS pr JOIN _accounts AS a ON pr.author_id = a.account_id WHERE $__timeFilter(merged_date) UNION SELECT CAST(prc.created_date AS DATE) AS Date, prc.created_date AS Time, 'Comment on PR' AS Activity, CONCAT('#', pr.pull_request_key, ' ', pr.title) AS Details, a.name AS Name FROM pull_request_comments AS prc LEFT JOIN pull_requests AS pr ON prc.pull_request_id = pr.id JOIN _accounts AS a ON prc.account_id = a.account_id WHERE prc.type = 'NORMAL' AND $__timeFilter(prc.created_date) UNION SELECT CAST(prc.created_date AS DATE) AS Date, prc.created_date AS Time, 'Review PR' AS Activity, CONCAT('#', pr.pull_request_key, ' ', pr.title) AS Details, a.name AS Name FROM pull_request_comments AS prc LEFT JOIN pull_requests AS pr ON prc.pull_request_id = pr.id JOIN _accounts AS a ON prc.account_id = a.account_id WHERE prc.type IN ('REVIEW', 'DIFF') AND $__timeFilter(prc.created_date)) AS t ORDER BY Time DESC NULLS LAST), _activities_per_day AS (SELECT Date, SUM(CASE WHEN Activity = 'Create an issue' THEN 1 ELSE 0 END) AS \"Create an issue\", SUM(CASE WHEN Activity = 'Issue resolved' THEN 1 ELSE 0 END) AS \"Issue resolved\", SUM(CASE WHEN Activity = 'Finish a commit' THEN 1 ELSE 0 END) AS \"Finish a commit\", SUM(CASE WHEN Activity = 'Open a PR' THEN 1 ELSE 0 END) AS \"Open a PR\", SUM(CASE WHEN Activity = 'PR gets merged' THEN 1 ELSE 0 END) AS \"PR gets merged\", SUM(CASE WHEN Activity = 'Comment on PR' THEN 1 ELSE 0 END) AS \"Comment on PR\", SUM(CASE WHEN Activity = 'Review PR' THEN 1 ELSE 0 END) AS \"Review PR\" FROM _activities GROUP BY 1), _calendar_dates AS (/* construct the last few calendar months within the selected time period in the top-right corner */ SELECT CAST(($__timeTo()::timestamp - INTERVAL '1 day') AS DATE) AS Date FROM (SELECT 0 AS H UNION ALL SELECT 100 UNION ALL SELECT 200 UNION ALL SELECT 300) AS H CROSS JOIN (SELECT 0 AS T UNION ALL SELECT 10 UNION ALL SELECT 20 UNION ALL SELECT 30 UNION ALL SELECT 40 UNION ALL SELECT 50 UNION ALL SELECT 60 UNION ALL SELECT 70 UNION ALL SELECT 80 UNION ALL SELECT 90) AS T CROSS JOIN (SELECT 0 AS U UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS U WHERE ($__timeTo()::timestamp - INTERVAL '1 day') > $__timeFrom()), _last_7_days AS (SELECT * FROM _calendar_dates ORDER BY Date DESC NULLS LAST LIMIT 7) SELECT TO_CHAR(_last_7_days.Date, '%d/%m %a') AS d, _activities_per_day.* FROM _last_7_days LEFT JOIN _activities_per_day ON _last_7_days.Date = _activities_per_day.Date ORDER BY _last_7_days.Date ASC NULLS FIRST"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Statuses of assigned issues",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "WITH _accounts AS (SELECT ua.account_id, ua.user_id, u.name FROM accounts AS a JOIN user_accounts AS ua ON a.id = ua.account_id JOIN users AS u ON ua.user_id = u.id WHERE ua.user_id IN ($users)), _issues AS (SELECT TO_CHAR(created_date, '%d/%m/%Y') AS Date, created_date AS Time, 'Create an issue' AS Activity, CONCAT('#', issue_key, ' ', title) AS Details, status, a.name AS Name FROM issues AS i JOIN _accounts AS a ON i.creator_id = a.account_id WHERE $__timeFilter(created_date)) SELECT status, COUNT(*) FROM _issues GROUP BY 1"
    }
   ]
  },
  {
   "title": "Code commits",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 33 },
   "targets": [
    {
     "rawSql": "WITH _accounts AS (SELECT ua.account_id, ua.user_id, u.name, u.email FROM accounts AS a JOIN user_accounts AS ua ON a.id = ua.account_id JOIN users AS u ON ua.user_id = u.id WHERE ua.user_id IN ($users)) SELECT COUNT(DISTINCT c.sha) FROM commits AS c JOIN _accounts AS a ON c.author_id = a.email WHERE $__timeFilter(authored_date)"
    }
   ]
  },
  {
   "title": "Lines of code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH _accounts AS (SELECT ua.account_id, ua.user_id, u.name FROM accounts AS a JOIN user_accounts AS ua ON a.id = ua.account_id JOIN users AS u ON ua.user_id = u.id WHERE ua.user_id IN ($users)), _commits AS (SELECT DISTINCT TO_CHAR(authored_date, '%d/%m/%Y') AS Date, authored_date AS Time, 'Finish a commit' AS Activity, CONCAT(message, ' #', sha) AS Details, a.name AS Name, c.additions, c.deletions FROM commits AS c JOIN _accounts AS a ON c.author_id = a.account_id WHERE $__timeFilter(authored_date)) SELECT SUM(additions + deletions) FROM _commits"
    }
   ]
  },
  {
   "title": "The count of PRs reviewed or commented by the selected users / Total PRs created within this timeframe.",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH _accounts AS (SELECT ua.account_id, ua.user_id, u.name FROM accounts AS a JOIN user_accounts AS ua ON a.id = ua.account_id JOIN users AS u ON ua.user_id = u.id WHERE ua.user_id IN ($users)), _prs AS (SELECT pr.id AS pr_id, pr.merged_date, CONCAT('#', pr.pull_request_key, ' ', pr.title) AS details, prc.id AS comment_id, prc.created_date AS comment_date, a.name, prc.type AS comment_type FROM pull_requests AS pr LEFT JOIN pull_request_comments AS prc ON pr.id = prc.pull_request_id LEFT JOIN _accounts AS a ON prc.account_id = a.account_id WHERE $__timeFilter(pr.created_date)) SELECT CONCAT(COUNT(DISTINCT CASE WHEN NOT name IS NULL THEN pr_id END), '/', COUNT(DISTINCT pr_id)) AS text FROM _prs"
    }
   ]
  },
  {
   "title": "PRs merged / PRs created by the selected users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH _accounts AS (SELECT ua.account_id, ua.user_id, u.name FROM accounts AS a JOIN user_accounts AS ua ON a.id = ua.account_id JOIN users AS u ON ua.user_id = u.id WHERE ua.user_id IN ($users)), _prs AS (SELECT DISTINCT TO_CHAR(created_date, '%d/%m/%Y') AS Date, created_date AS Time, 'Open a PR' AS Activity, CONCAT('#', pull_request_key, ' ', title) AS Details, a.name AS Name, pr.id, pr.merged_date FROM pull_requests AS pr JOIN _accounts AS a ON pr.author_id = a.account_id WHERE $__timeFilter(created_date)) SELECT CONCAT(COUNT(CASE WHEN NOT merged_date IS NULL THEN id ELSE NULL END), '/', COUNT(DISTINCT id)) FROM _prs"
    }
   ]
  },
  {
   "title": "The monthly count of PRs merged out of the total created by the selected users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 41 },
   "targets": [
    {
     "rawSql": "WITH _accounts AS (SELECT ua.account_id, ua.user_id, u.name FROM accounts AS a JOIN user_accounts AS ua ON a.id = ua.account_id JOIN users AS u ON ua.user_id = u.id WHERE ua.user_id IN ($users)), _prs AS (SELECT CAST(created_date AS DATE) + INTERVAL '1 day' AS time, COUNT(DISTINCT pr.id) AS pr_count FROM pull_requests AS pr JOIN _accounts AS a ON pr.author_id = a.account_id WHERE $__timeFilter(created_date) AND /*  and created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH) */ NOT pr.merged_date IS NULL GROUP BY 1) SELECT TO_CHAR(time, '%M %Y') AS month, pr_count AS \"Pull Request Count\" FROM _prs ORDER BY time NULLS FIRST"
    }
   ]
  },
  { "title": "Batch Size and Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Average PR merged size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "lines of code" } },
   "targets": [
    {
     "rawSql": "WITH _accounts AS (SELECT ua.account_id, ua.user_id, u.name FROM accounts AS a JOIN user_accounts AS ua ON a.id = ua.account_id JOIN users AS u ON ua.user_id = u.id WHERE ua.user_id IN ($users)), _commits AS (SELECT DISTINCT TO_CHAR(authored_date, '%d/%m/%Y') AS Date, authored_date AS Time, 'Finish a commit' AS Activity, CONCAT(message, ' #', sha) AS Details, a.name AS Name, c.additions, c.deletions, c.sha FROM commits AS c JOIN _accounts AS a ON c.author_id = a.account_id WHERE $__timeFilter(authored_date)), _pr_commits_data AS (SELECT pr.id AS pr_id, pr.merge_commit_sha, SUM(c.additions) + SUM(c.deletions) AS loc FROM pull_requests AS pr LEFT JOIN _commits AS c ON pr.merge_commit_sha = c.sha WHERE $__timeFilter(pr.created_date) AND pr.status = 'MERGED' GROUP BY 1, 2) SELECT AVG(loc) AS \"PR Merged Size\" FROM _pr_commits_data"
    }
   ]
  },
  {
   "title": "Average review depth",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "comments per PR" } },
   "targets": [
    {
     "rawSql": "WITH _accounts AS (SELECT ua.account_id, ua.user_id, u.name FROM accounts AS a JOIN user_accounts AS ua ON a.id = ua.account_id JOIN users AS u ON ua.user_id = u.id WHERE ua.user_id IN ($users)), _prs AS (SELECT TO_CHAR(prc.created_date, '%d/%m/%Y') AS Date, prc.created_date AS Time, 'Comment on PR' AS Activity, CONCAT('#', pr.pull_request_key, ' ', pr.title) AS Details, a.name AS Name, pr.id AS pr_id, prc.id AS prc_id FROM pull_request_comments AS prc LEFT JOIN pull_requests AS pr ON prc.pull_request_id = pr.id JOIN _accounts AS a ON prc.account_id = a.account_id WHERE $__timeFilter(prc.created_date)) SELECT ROUND(CAST(COUNT(DISTINCT prc_id) AS NUMERIC) / NULLIF(COUNT(DISTINCT pr_id), 0), 1) FROM _prs"
    }
   ]
  },
  {
   "title": "Average PR time to merge",
   "type": "stat",
   "description": "average pr review time from first comment to the last comment",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "WITH _accounts AS (SELECT ua.account_id, ua.user_id, u.name FROM accounts AS a JOIN user_accounts AS ua ON a.id = ua.account_id JOIN users AS u ON ua.user_id = u.id WHERE ua.user_id IN ($users)) SELECT AVG(CAST((EXTRACT(EPOCH FROM (pr.merged_date - pr.created_date))/60) AS NUMERIC) / NULLIF(60, 0)) AS \"Time to merge\" FROM pull_requests AS pr JOIN _accounts AS a ON pr.author_id = a.account_id WHERE $__timeFilter(pr.created_date)"
    }
   ]
  }
 ]
}